### ISSUE TITLE
Dai as a display currency

### ISSUE THREAD

**Issue by alextes** [rainbow-me/rainbow#1117]
I would love to have Dai as a display currency option.

For me personally, I'm really down with the whole bankless story, if we're to move on from fiat currencies being the default, Dai needs to be at least an option for people to use. I happened to send the feedback in an email before I knew rainbow.me was open-source 🙌 🌈 ! The response to that email was positive.

So what do you say? Open to a PR maybe too?

**Comment by skylarbarrera** [comment]
Thanks for your interest in 🌈  @alextes  ! Unfortunately we are limited to the assets supported by our Data Providers, we would love to add native Dai support and will once we are able! In the meantime you may be interested to know that we just added support for 7 new native currencies https://github.com/rainbow-me/rainbow/pull/1267
