### ISSUE TITLE
add Network POA XDAI

### ISSUE THREAD

**Issue by developerfred** [rainbow-me/rainbow#1259]
As an [xDai Network ](https://blockscout.com/poa/xdai/) user I would love to see my tokens through the RainBow wallet

ref: https://www.xdaichain.com/

**Comment by skylarbarrera** [comment]
Hey @developerfred ,

Thanks for your interest in 🌈 ! 
We're currently focusing on building out features that we think are essential for the best mobile wallet experience! 
That being said we are keeping an eye on xDAI and other networks and hope to implement them when possible! 🚀

Thanks again and keep your eyes 🍌 !

🌈
