### ISSUE TITLE
incorrect chain id on Görli

### ISSUE THREAD

**Issue by azat-s** [rainbow-me/rainbow#1377]
iOS Rainbow wallet on Görli network passes incorrect chain id when connecting to a dapp (e.g. Uniswap).

## Replication

1. Download Rainbow wallet app from AppStore
2. Create a new Ethereum wallet or import an existing one
3. Switch to Görli network in settings
4. Go to https://app.uniswap.org/#/swap in your desktop browser
5. Click _Connect to a wallet_
6. Open QR reader inside Rainbow app on mobile
7. Scan QR
8. Allow the app to connect to Uniswap

## Expected result

Uniswap should show that you are on the wrong network because it only works with Ethereum Mainnet.

## Current result

Uniswap shows that you are on the correct network.

## More

I also tested this using a dapp that I built myself. When I connect to my dapp using Rainbow wallet on Görli, the provider returns chainId of 1, instead of 5. This is not a WalletConnect issue, I tested it using https://test.walletconnect.org/ and the provider returns correct chainId of 5.

## 
OS: iOS
Version: 1.2.39 (51)

**Comment by skylarbarrera** [comment]
Hey @azat-s , thanks for using 🌈 !

We recently pushed a fix to this issue and we will make sure it's part of our next update!
