### ISSUE TITLE
[WalletConnect] Nonce not respected

### ISSUE THREAD

**Issue by teohhanhui** [rainbow-me/rainbow#1521]
**Scenario**:
Using https://cancel-ethereum-transactions.web.app/ to speed up or cancel a transaction.

**Expected result**:
Nonce set by dapp is respected.

**Actual result**:
Nonce set by dapp is not respected.

**Example**:
Original transaction: https://etherscan.io/tx/0x2f703b2cd455e44a07caca3f1dcd33c6cfa2d88f6d6e344c5744c3b151823fad
Attempt to speed up transaction with Rainbow (wrong nonce): https://etherscan.io/tx/0x50d5f5d471857158681ea6674956fbf05afa9a55d1da33d9a89f5c03cc97225c
Attempt to speed up transaction with Trust Wallet (correct nonce): https://etherscan.io/tx/0xfc0083e05a974f8b594a5d99d4bf182bbef0701ae6719381a058fe1388cf272d

**Rainbow version**:
Android; 1.0 (11)

**Comment by skylarbarrera** [comment]
Hey @teohhanhui,

Thanks for using 🌈 !

We recently added speed up & cancel functionality to Rainbow so hopefully you won't have to use a dApp anymore: https://github.com/rainbow-me/rainbow/pull/1517

We plan on adding more advanced features like setting custom nonce for canceling transactions soon as well!

Hope this will help you moving forward and thanks again for using 🌈 !
