### ISSUE TITLE
[Android][WalletConnect] "Failed to send transaction"

### ISSUE THREAD

**Issue by teohhanhui** [rainbow-me/rainbow#1551]
Got error message "Failed to send transaction" when trying to swap on 1inch DEX.

EDIT: Actually, all WalletConnect transactions seem to give the same error.

![Screenshot_20210109-153035](https://user-images.githubusercontent.com/548843/104086093-ad866880-528f-11eb-9176-c6aa90336e08.png)

**Comment by skylarbarrera** [comment]
Hey @teohhanhui 

Thanks again for reporting all the 🐛's  you find!

We've since released an update to the 🤖  app that fixes this issue and everything should be functioning as expected now.

Thanks for using 🌈  and keep in touch!
