### ISSUE TITLE
[Android] Wrong overlay size when using split screen

### ISSUE THREAD

**Issue by teohhanhui** [rainbow-me/rainbow#1576]
It is cut off at the top.

![Screenshot_20210114-020401](https://user-images.githubusercontent.com/548843/104491349-144baf00-560d-11eb-88a9-1d3c443cffc8.png)

**Comment by skylarbarrera** [comment]
Hey @teohhanhui ,

**Comment by skylarbarrera** [comment]
Hey @teohhanhui ,

Thanks again for reporting your findings!

We are currently focused on increasing android stability & performance while also working on some new core features! We will add this to our backlog!

Thanks for using 🌈 !
