### ISSUE TITLE
[IOS] App is crashing trying to sign transaction using Wallet Connect

### ISSUE THREAD

**Issue by ochikov** [rainbow-me/rainbow#1582]
IOS: 13.5.1
Model: iPhone 7 Plus
Installed App Version: 1.2.46

When connecting to the wallet with the Wallet Connect through the app and tried to sign a transaction, the app is crashing and closing by itself.

**Comment by skylarbarrera** [comment]
Hey @ochikov,

Thanks for using 🌈 !

Sorry you ran into that, but thanks for reporting!

 We've got a fix that will be in our next update in the coming days: #1583
