### ISSUE TITLE
More info on savings (Android app)

### ISSUE THREAD

**Issue by excogitation** [rainbow-me/rainbow#1597]
Wouldn't it make sense to show more information on the investments as the 9.6%APY do certainly
sound interesting but this does not suffice in my opinion.

![image](https://user-images.githubusercontent.com/1671762/104824882-3edc7880-5856-11eb-8f5b-4e5229511435.png)

**Comment by jinchung** [comment]
Thanks for your comment! We'd love to hear your thoughts on what other details might help! What would be some information that would help you feel more confident or interested in interacting with Savings?

**Comment by excogitation** [comment]
I think it should show the provider used
https://defirate.com/dai/
and a link to some easy explanation of DeFi lending.
Does the user also earn compound tokens?

**Comment by skylarbarrera** [comment]
@excogitation 

These are great points and we've got a big updating that should make this more clear for users!
