### ISSUE TITLE
detailed investment cost information (Android)

### ISSUE THREAD

**Issue by excogitation** [rainbow-me/rainbow#1598]
this is the screen I assume right before depositing DAI into savings.
![image](https://user-images.githubusercontent.com/1671762/104824955-e063ca00-5856-11eb-9e94-ce1e4780a0ea.png)

It is not clear how much money will end up in savings but it should be clearly shown.
I assume 100.35 - 51.58 = 48,77.

Also - it would make sense to show break even time here.
(10 months to recover the 51.58$ if the interest is stable).

**Comment by jinchung** [comment]
Thanks again for the feedback! 

Just as a heads up, I responded to one of your issues on: https://github.com/rainbow-me/rainbow/issues/1599
There, I mentioned that the Ethereum network fees are paid in ETH. For this deposit, the network fees would be taken from ETH in your account, but the amount of DAI you deposit will remain the same. So, you will be depositing exactly 100 DAI into savings (regardless of the cost of the network fees.) The network fees can vary depending on what sort of transaction you are doing as well as by how busy the network currently is. At the time of your screenshot, it seems the network was extremely busy, causing the ETH fees to be quite high.

We are currently in the design process for helping users understand the concept of "gas" (paying the Ethereum network fees in ETH). Hope this helps, thanks!

**Comment by excogitation** [comment]
@jinchung: I hacked this together real quick - maybe it can serve as inspiration.
![image](https://user-images.githubusercontent.com/1671762/104966249-b50ce680-59e0-11eb-8a2f-da78b945a253.png)

https://www.figma.com/file/v2fwOdPjikTJuQvWVgdzan/Rainbow-me-design-hacks?node-id=0%3A1

yes, the shown transaction fees seem to be very high and even a lot higher than
https://ycharts.com/indicators/ethereum_average_transaction_fee

I ended up paying
![image](https://user-images.githubusercontent.com/1671762/104966705-dfab6f00-59e1-11eb-93c1-5b60cb1835fb.png)
which I think is less the amount displayed in the app.

**Comment by skylarbarrera** [comment]
@excogitation  We really appreciate you throwing that together, very cool stuff!

We're looking into making this clearer going forward, especially for users that are new to Ethereum!
