### ISSUE TITLE
swapping coins not correctly displayed (Android)

### ISSUE THREAD

**Issue by excogitation** [rainbow-me/rainbow#1599]
Swapping ETH to DAI
![image](https://user-images.githubusercontent.com/1671762/104827328-b8776500-585c-11eb-8d84-75967aaa81dc.png)
0.1 ETH to DAI apparently the fees get substracted before the swap from the source value which is wrong.
Also will 112.071 DAI be the credited amount after the swap or  112.071DAI - $12.59 (converted to DAI)?
![image](https://user-images.githubusercontent.com/1671762/104827002-c2e42f80-5859-11eb-9d81-c48c9b1cf387.png)

**Comment by jinchung** [comment]
Hey, thanks for using Rainbow and for your feedback!

ETH is what is used for paying the Ethereum network fees, so if you are attempting to send the max amount of your ETH, some portion of it will need to be set aside to pay for the fees. If you do not, then you will not have enough to pay for the network fees, and your transaction will be rejected from the network. This is why we automatically deduct this for you when the intent is to send the max amount of ETH, to prevent unnecessary transaction failures. The 112.071 DAI that is shown is the amount that will be credited (it is based on the $112.13 worth of ETH that will be swapped.)

We are currently working on an updated swap details view where you can see more information about the swap! Let us know if you have any other questions related to this, thanks!

**Comment by excogitation** [comment]
@jinchung: It is self explanatory to you and it makes sense. For somebody new the expectancy would be to have the same number in the swap box as in the funding wallet after clicking max.

same as before ... for inspiration purposes:
![image](https://user-images.githubusercontent.com/1671762/104968477-40d54180-59e6-11eb-9dbe-fa17d1051268.png)

https://www.figma.com/file/v2fwOdPjikTJuQvWVgdzan/Rainbow-me-design-hacks?node-id=208%3A2
