### ISSUE TITLE
Camera permission not asked again (Android)

### ISSUE THREAD

**Issue by ligi** [rainbow-me/rainbow#1600]
When you once deny the camera permission you get not asked again. Also it enters the scan activity with a black screen.
IMHO - on deny it should not enter the activity and if you click on scan again it should ask for the permission again
currently you need to kill the activity to be asked again

**Comment by skylarbarrera** [comment]
Hey @ligi ,

Thanks for checking out 🌈  !

This is a great point, we will look into this as this makes sense. Currently if you reload the app after denying camera permission it will ask again.

Hopefully this will get you up and running for now!
