### ISSUE TITLE
Savings amount incorrectly shows $0.00 (Android)

### ISSUE THREAD

**Issue by excogitation** [rainbow-me/rainbow#1609]
Sometimes the savings amount is not shown correctly.
![image](https://user-images.githubusercontent.com/1671762/105004377-2c1f9a80-5a34-11eb-85cf-7baecf991ded.png)

clicking expanding it does show the correct amount but clearly with some data missing.

![image](https://user-images.githubusercontent.com/1671762/105004322-1a3df780-5a34-11eb-865f-56a646d316b7.png)

**Comment by skylarbarrera** [comment]
Hey @excogitation,

Thanks again 🌈  !

We are aware of this and from the looks of it this was an issue we thought we had addressed, can you confirm you are on the latest version?

 We'll look into this!

**Comment by excogitation** [comment]
I am on 1.0 (18) and there is no rainbow 🌈 update in the play store.

**Comment by teohhanhui** [comment]
![Screenshot_20210217-140009](https://user-images.githubusercontent.com/548843/108162640-7f1a6980-7128-11eb-84d6-fa4713e09270.png)

I have staked DPI/ETH but it's not showing up. (It was showing up before.)

**Comment by skylarbarrera** [comment]
Hey @excogitation , 

This should be resolved now!

@teohhanhui We are aware of a delay in Pool info and are working on making 🌈  update this info faster!

Thanks for the feedback ❤️
