### ISSUE TITLE
Delete wallet not working correctly

### ISSUE THREAD

**Issue by Eratos1122** [rainbow-me/rainbow#1631]
It requires the biometric to remove the wallet.
But I just closed the app without passing the biometric verification
After that, the app doesn't work correctly - it says `Initializing...`

Since I am a blockchain & web & mobile developer, I can fix it and make a PR

**Comment by skylarbarrera** [comment]
Hey @Eratos1122, 

Thanks so much for bringing this to our attention! We've merged a fix: https://github.com/rainbow-me/rainbow/commit/8ec32cddc62f3c84cd62271a12c8e486ac49ee82

And will be release an update to the Apple App Store & Google Play very soon!
