### ISSUE TITLE
How to export an account

### ISSUE THREAD

**Issue by mudgen** [rainbow-me/rainbow#1637]
Hello,

Is there a way to export an account in rainbow and import it into Metamask?

**Comment by skylarbarrera** [comment]
Hey @mudgen 

If you open Settings -> Back Up in  🌈  , you will be able to access your seed phrase which can be imported into Metamask or any other self custody wallet!

Go ahead and give it a try and close this issue if that works for you!

**Comment by bitbodhe** [comment]
Hey @skylarbarrera! I imported my wallet with a seed phrase, but it just opens an empty wallet for me in Metamask. 

![Screenshot_2021-01-27_at_13 14 18](https://user-images.githubusercontent.com/78113345/106055730-a5f1fc80-60a2-11eb-9e4b-15b0078524e9.png)

**Comment by mudgen** [comment]
@skylarbarrera Any suggestions?

**Comment by skylarbarrera** [comment]
@mudgen @bitbodhe 

This seem's to be a Metamask Issue, from the following it looks like you'll need to click add another account until all of your wallets show up.

Here's the related issue: https://github.com/MetaMask/metamask-extension/issues/2641#issuecomment-352545382

If you still need help, go ahead and email support@rainbow.me and I can help you more privately!

**Comment by mudgen** [comment]
> @mudgen @bitbodhe
> 
> This seems to be a Metamask Issue, from the following it looks like you'll need to click add another account until all of your wallets show up.
> 
> Here's the related issue: [MetaMask/metamask-extension#2641 (comment)](https://github.com/MetaMask/metamask-extension/issues/2641#issuecomment-352545382)
> 
> If you still need help, go ahead and email [support@rainbow.me](mailto:support@rainbow.me) and I can help you more privately!

You are correct and this worked. Thank you so much for your help!
