### ISSUE TITLE
Missing StyleSheet Import in DiscoverSheet.js

### ISSUE THREAD

**Issue by zifahm** [rainbow-me/rainbow#1656]
There seems to be a missing StyleSheet Import in DiscoverSheet.js
Solution:  import { StyleSheet }  from 'react-native'

I found this out while trying to turn on discover sheet under developer setting, but after making the import available, there seems to be lot other porblems like undefined token in CoinIconGroup, Seems like a hard fix, still figuring out where are things getting undefined.

**Comment by zifahm** [comment]
I must say a typescript would make issues like this go away for sure.

**Comment by zifahm** [comment]
This is for Android btw

**Comment by skylarbarrera** [comment]
Hey @zifahm ,

Thanks for reaching out! We are aware of this issue and have been working on Discover on a separate feature branch: https://github.com/rainbow-me/rainbow/pull/1498

If you'd like to explore please be aware that this feature is still in active development!
