### ISSUE TITLE
Protecting sensitive information in .env

### ISSUE THREAD

**Issue by arberK** [rainbow-me/rainbow#1731]
Hi, 

this might be a little off-topic, but I was wandering around the Rainbow code and I noticed that you use some sensitive information in .env (e.g. RAINBOW_MASTER_KEY).  I was wondering how do you secure those sensitive infos? AFAIK, environment variables are bundled in js-bundle, hence anyone can see them, which it will even become super-easier if one uses OTA-Updates.

Thank you in advance. Feel free to close this issue if you think its not worthy in the issues section.

**Comment by skylarbarrera** [comment]
Hey @arberK, 

Thanks for reaching out! 
We're actively working on making 🌈  the most secure mobile wallet and this is a big part of that!
