### ISSUE TITLE
Unable to import seed phrase (iOS)

### ISSUE THREAD

**Issue by sachayves** [rainbow-me/rainbow#1756]
12 word phrase; import button doesn't respond (stays grey).

**Comment by sachayves** [comment]
My bad. I misspelt one word. would be useful to have some feedback though. Something like: `this is not a valid seed phrase, please double check the words you've entered are spelt correctly`

**Comment by skylarbarrera** [comment]
Hey @sachayves ,

You're right, Thanks for the feedback! Glad everything is working now!
