### ISSUE TITLE
Apple Pay Eth purchase failing after 'Running Checks' stage

### ISSUE THREAD

**Issue by jonathanprozzi** [rainbow-me/rainbow#1820]
Hello - I was trying to purchase Eth with Apple Pay and noticed that the transaction seems to be approved via Apple (moves into the _Running Checks_ stage, but then fails with an error of "Do Not Honor." There is a series of failed transactions to Wyre in my Apple Wallet, and I have adequate funds (and tried with a lower amount incase the fees had changed). I've also used Apple Pay for other uses to test if it was something with my Apple Pay. 

I noticed some people mentioning this on Twitter but figured I'd file an issue (apologies if this wasn't the best way -- I didn't want to also add a note on Twitter and I know I'd have preferred an issue on GitHub!) 

Fantastic product by the way - I love everything about it!

**Comment by skylarbarrera** [comment]
Hey @jonathanprozzi,

Thanks for using 🌈 !

Our payment's processor has some restrictions based on location, card type & bank. You most likely ran into one of these restrictions!

We are currently working on making the error messaging more informative to what the precise issue is and we also are planning to add support for more regions & payment options ~very~ soon!

For now we would suggest that you use a centralized exchange like Gemini or Coinbase to buy ETH and then send it to your 🌈 address 🙂

**Comment by jonathanprozzi** [comment]
Great! Thanks for the quick response on this. Appreciated!
