### ISSUE TITLE
Help: Can someone help me with building for android? [help wanted] [android]

### ISSUE THREAD

**Issue by l3gacyb3ta** [rainbow-me/rainbow#1829]
Sorry, I'm a noob at app dev. Does anyone have a tutorial or, better yet, a prebuilt apk?

**Comment by skylarbarrera** [comment]
Hey @l3gacyb3ta ,

You can follow our README for building instructions https://github.com/rainbow-me/rainbow/blob/develop/README.md

Be sure to checkout the RN docs for env setup: https://reactnative.dev/docs/environment-setup#target-os-2


You can also sign up for the android beta @ [rainbow.me](rainbow.me)

**Comment by l3gacyb3ta** [comment]
Thanks!
