### ISSUE TITLE
Token balance not updating

### ISSUE THREAD

**Issue by twodayslate** [rainbow-me/rainbow#1866]
With tokens like [BUNNY](https://www.coingecko.com/en/coins/rocket-bunny) that has automatic yields my balance is not being updated. This means I can't swap the correct/max amount.

**Comment by skylarbarrera** [comment]
Hey @twodayslate ,

Keeping track of all the token's on Ethereum is hard! We'll look into this on our end and see if we can fix for you!

We use Zerion to help with this, you may want to reach out to them as well!

Thanks for using 🌈
