### ISSUE TITLE
errors when purchasing ethereum on my ipad

### ISSUE THREAD

**Issue by reachlin** [rainbow-me/rainbow#1913]
![7FC82807-1471-48A5-9503-15AEC6D09DA6](https://user-images.githubusercontent.com/1051988/112706663-b119ab00-8ee0-11eb-88c8-8bfecdb343cf.png)
pls help

**Comment by Montecrysto** [comment]
And where did it start?

**Comment by skylarbarrera** [comment]
Hey @reachlin ,

Thanks for using 🌈 !

Our payment's processor has some restrictions based on location, card type & bank. 
That being said you can confirm your Apple Pay # is a valid mobile # by tapping edit on the Apple Pay model when you go to purchase!

We are currently working on making the error messaging more informative to what the precise issue is and we also are planning to add support for more regions & payment options very soon!

For now we would suggest that you use a centralized exchange like Gemini or Coinbase to buy ETH and then send it to your 🌈 address!
