### ISSUE TITLE
Error on `yarn setup` during build

### ISSUE THREAD

**Issue by loganbek** [rainbow-me/rainbow#1955]
I'm receiving the following error when running `yarn setup`. In particular, it looks like the `yarn allow-scripts` command is failing w/ code 1 but I'm not sure why or how to fix it:

```
[4/4] 🔨  Building fresh packages...
warning Ignored scripts due to flag.
$ /Users/loganbek/Desktop/rainbow/node_modules/.bin/allow-scripts
no allowed scripts found in configuration
running lifecycle scripts for top level package
Error: command failed
    at ChildProcess.<anonymous> (/Users/loganbek/Desktop/rainbow/node_modules/@npmcli/promise-spawn/index.js:64:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  cmd: 'sh',
  args: [ '-c', './scripts/postinstall.sh' ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: '',
  event: 'postinstall',
  script: './scripts/postinstall.sh',
  pkgid: 'Rainbow@1.5.2-1',
  path: '/Users/loganbek/Desktop/rainbow'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I followed the README build instructions and always seem to have an issue w/ this step. This happens in both rainbow and my forked rainbow repository. The rest of the build seems to work fine. Any help or suggestions would be greatly appreciated. Thanks!

**Comment by dodoecb2** [comment]
Type after "Yarn setup", even giving an error.

`sh ./scripts/postinstall.sh`

**Comment by dodoecb2** [comment]
> @dodoecb2, thanks for the reply. That command runs fine, although I'd like to get `yarn setup` functioning correctly if possible.

Try: chmod 777 ./scripts/postinstall.sh OR

```
git update-index --add --chmod=777 scripts/postinstall.sh
git commit -m 'postinstall.sh fix'
git push
```

**Comment by loganbek** [comment]
Thanks for your help @dodoecb2. I believe the issue was w/ `grep` failing for "CODEPUSH" and "GOOGLE" in postinstall.sh and not a permissions issue.
