### ISSUE TITLE
Support for ERC-712 

### ISSUE THREAD

**Issue by Nipol** [rainbow-me/rainbow#197]
dydx requires the user to sign based on ERC-712.
Rainbow does not support ERC-712 and provides a very brief overview of the signature data.
<img width="472" alt="스크린샷 2019-10-28 오후 2 07 03" src="https://user-images.githubusercontent.com/693461/67653507-0a4c7a80-f98d-11e9-96e6-d33b78875dc5.png">
(metamask)
![IMG_2120](https://user-images.githubusercontent.com/693461/67653531-1cc6b400-f98d-11e9-8e88-502064aebeda.PNG)
(The above pictures capture the same request shown in Metamask and Rainbow.)
Also, if sign it, the dydx cannot interpret it, because the data need to sign is different.

**Comment by brunobar79** [comment]
This issue has been fixed on 1.2.7 which is currently under review in the App Store.
