### ISSUE TITLE
Recovering a Damaged Wallet

### ISSUE THREAD

**Issue by darnfish** [rainbow-me/rainbow#1976]
Is it possible to recover a damaged wallet?

**Comment by skylarbarrera** [comment]
hey @darnfish , 

There are a few ways, can you reach out to us via support@rainbow.me and we'll help you walk through them?

Thanks for using 🌈 !

**Comment by darnfish** [comment]
Sure, been emailing for a couple days :~)

**Comment by darnfish** [comment]
@skylarbarrera I've been contacting the support email for over a month and I haven't received any response. Could you reach out to me, william@tired.io. Thanks
