### ISSUE TITLE
Unidentified contract info

### ISSUE THREAD

**Issue by bcomnes** [rainbow-me/rainbow#1978]
I own an NFT but it shows up as unidentified contract in rainbow wallet.  Is there something the contract owner can do to set up a name/logo for it?

Here is the contract in question: https://opensea.io/assets/0x33a4cfc925ad40e5bb2b9b2462d7a1a5a5da4476/57896044618658097711785492504343953929697533635108728192504030205255209713665

**Comment by bcomnes** [comment]
Here is an example

![IMG_7083](https://user-images.githubusercontent.com/166301/115909104-45b3f200-a428-11eb-8202-cf4099fe75ec.PNG)

**Comment by skylarbarrera** [comment]
We're aware of this issue, working on a fix! Should be in our next update! 
Thanks for reporting!  🙂  

🌈
