### ISSUE TITLE
Option to disable the "Discover" screen

### ISSUE THREAD

**Issue by fskaeh** [rainbow-me/rainbow#1979]
Hello,
Would it be possible to introduce a setting to remove the Discover screen? I like Rainbow Wallet for being a simple wallet app with a sleek UI, but this new section looks like a Time's Square electronic billboard with all sorts of stuff scrolling through endlessly which I don't think is needed by everyone. I liked that swiping towards the left would show the QR code scanner directly.
Just my two cents, thank you!

**Comment by skylarbarrera** [comment]
Hey @fskaeh, 

Unfortunately we have no plans to allow disabling of the discover page, we view it as an integral part of 🌈 !
