### ISSUE TITLE
Build error: duplicate symbol in CocoaAsyncSocket/libCocoaAsyncSocket.a(GCDAsyncUdpSocket.o)

### ISSUE THREAD

**Issue by bidah** [rainbow-me/rainbow#1985]
Hey there!, I am trying to run the app but getting this error.

duplicate symbol '_OBJC_IVAR_$_GCDAsyncUdpSendPacket.resolveError' in:
    Xcode/DerivedData/Rainbow-brsdvdrkbzohnubaxsbqmjxotjzo/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket/libCocoaAsyncSocket.a(GCDAsyncUdpSocket.o)
Looking around found that if I go to Pods > TcpSockets > Build Phases > Compile sources and delete CocoaAsyncSocket a chuck of the duplicates go away but there are at least 64 remaining.

Looks like the last thing to get this going! any help welcomed!

**Comment by skylarbarrera** [comment]
Hey @bidah, 

We're not running into this on our end, can you try pulling the latest and confirm everything is working on your end?

Thanks for checking out 🌈 !
