### ISSUE TITLE
Rainbow doesn’t show balance on test networks

### ISSUE THREAD

**Issue by kenokenobingo** [rainbow-me/rainbow#1987]
When I set Rainbow to the Rinkeby test network, it doesn’t show my balance.

**Comment by skylarbarrera** [comment]
Hey @kenokenobingo,

This looks to have been an issue with our data provider, can you confirm everything is working for you now?

🌈

**Comment by kenokenobingo** [comment]
Thanks, @skylarbarrera! Unfortunately, it’s still not working.
![IMG_7F882CA73CDA-1](https://user-images.githubusercontent.com/9639767/122466723-f6b6b300-cfb9-11eb-9db6-1a446c514dd5.jpeg)
