### ISSUE TITLE
Running yarn start from setup instructions errors out

### ISSUE THREAD

**Issue by alexreyes** [rainbow-me/rainbow#2004]
I've been trying to run the Rainbow repo on my Mac (I want to contribute!) but I haven't been able to get the repo set up using the project instructions. I'm using an M1 Macbook air.

I've done the following from the instructions: 
- [x] A computer running macOS.
- [x] NVM installed or Node.js 14: https://github.com/creationix/nvm
- [x] Install CocoaPods by running sudo gem install cocoapods
- [x] Install Watchman brew install watchman
- [x] Install the latest version of XCode: https://developer.apple.com/xcode/
- [x] Clone the GitHub repository to your machine.
- [x] Run nvm use 14 to use set the version of node for this project. 
- [x] Setup .env 
- [ ] ``yarn setup`` <-- This is where the errors happen.

Breaking down ``yarn setup``, running ``yarn install`` works fine. The part that breaks is running ``yarn allow-scripts``. Running that, I get the following errors: 

```
➜  rainbow git:(develop) yarn allow-scripts
yarn run v1.22.10
$ /Users/hack/Local/rainbow/node_modules/.bin/allow-scripts
no allowed scripts found in configuration
running lifecycle scripts for top level package
Error: command failed
    at ChildProcess.<anonymous> (/Users/hack/Local/rainbow/node_modules/@npmcli/promise-spawn/index.js:64:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12) {
  cmd: 'sh',
  args: [ '-c', './scripts/postinstall.sh' ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: '',
  event: 'postinstall',
  script: './scripts/postinstall.sh',
  pkgid: 'Rainbow@1.5.7-1',
  path: '/Users/hack/Local/rainbow'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The ``package.json`` is the one from the latest commit in the develop branch. I've been stuck on this since yesterday, and haven't gotten it to work from the various attempts I've made, so hopefully someone can help!

**Comment by loganbek** [comment]
Hey @alexreyes, I had the same problem when trying to install a couple weeks ago. I believe I fixed it by modifying the following in `postinstall.sh`: 

```
#!/bin/bash
set -eo pipefail

if [ -e .env ]
then
  cat .env | grep "BRANCH" | sed 's/=/ = /g' > ./ios/debug.xcconfig
  cat .env | grep "BRANCH" | sed 's/=/ = /g' > ./ios/release.xcconfig
  cat .env | grep "BRANCH" | sed 's/=/ = /g' > ./ios/localrelease.xcconfig
  cat .env | grep "BRANCH" | sed 's/=/ = /g' > ./ios/staging.xcconfig

  # check BRANCH config
  # echo ".env BRANCH -> config"
  
  # cat .env | grep "CODEPUSH" | sed 's/=/ = /g' >> ./ios/debug.xcconfig
  # cat .env | grep "CODEPUSH" | sed 's/=/ = /g' >> ./ios/release.xcconfig
  # cat .env | grep "CODEPUSH" | sed 's/=/ = /g' >> ./ios/localrelease.xcconfig
  # cat .env | grep "CODEPUSH" | sed 's/=/ = /g' >> ./ios/staging.xcconfig

  # # check CODEPUSH config
  # echo ".env CODEPUSH -> config"

  # cat .env | grep "GOOGLE" | sed 's/=/ = /g' >> ./ios/debug.xcconfig
  # cat .env | grep "GOOGLE" | sed 's/=/ = /g' >> ./ios/release.xcconfig
  # cat .env | grep "GOOGLE" | sed 's/=/ = /g' >> ./ios/localrelease.xcconfig
  # cat .env | grep "GOOGLE" | sed 's/=/ = /g' >> ./ios/staging.xcconfig

  # check GOOGLE config
  # echo ".env GOOGLE -> config"

  echo "✅ .xcconfig files created"

  source .env
  echo "✅ Android ENV vars exported"

else
  echo "⚠️ .env file missing!! ⚠️"
  echo "Please make sure the file exists and it's located in the root of the project"
fi

if [ -n "$RAINBOW_SCRIPTS_APP_IOS_PREBUILD_HOOK" ]; then
  eval $RAINBOW_SCRIPTS_APP_IOS_PREBUILD_HOOK;
  echo "✅ executed ios prebuild hook"
fi
if [ -n "$RAINBOW_SCRIPTS_APP_ANDROID_PREBUILD_HOOK" ]; then
  eval $RAINBOW_SCRIPTS_APP_ANDROID_PREBUILD_HOOK;
  echo "✅ executed android prebuild hook"
fi

# Ignore any potential tracked changes to mutable development files.

git update-index --assume-unchanged "ios/Internals/ios/Internals.h"
git update-index --assume-unchanged "ios/Internals/ios/Internals.m"
git update-index --assume-unchanged "ios/Internals/ios/Internals.swift"
git update-index --assume-unchanged "ios/Internals/ios/Internals-Bridging-Header.h"
git update-index --assume-unchanged "ios/Extras.json"
git update-index --assume-unchanged "android/app/src/main/res/raw/extras.json"
git update-index --assume-unchanged "android/app/src/main/java/me/rainbow/NativeModules/Internals/InternalModule.java"
git update-index --assume-unchanged "android/app/src/main/java/me/rainbow/MainActivity.java"


# Specifying ONLY the node packages that we need to install via browserify
# (because those aren't available in react native) and some of our deps require them.
# If we don't specify which packages, rn-nodeify  will look into each package.json
# and install everything including a bunch devDeps that we don't need like "console"
rn-nodeify --install --hack 'crypto,buffer,react-native-randombytes,vm,stream,http,https,os,url,net,fs,process'
echo "✅ rn-nodeify packages hacked succesfully"

patch-package
echo "✅ All patches applied"

DEBUGFILE=src/config/debug.js
if test -f "$DEBUGFILE"; then
    echo "$DEBUGFILE exists."
else
    echo "$DEBUGFILE does not exist. You use default debug settings."
    cp src/config/defaultDebug.js $DEBUGFILE
fi

# Remove the incomplete installation
# of sentry-cli from node_modules
rm -rf node_modules/.bin/sentry-cli

if ! command -v sentry-cli &> /dev/null
then
  echo "Installing sentry-cli..."
  brew install getsentry/tools/sentry-cli
else
  which sentry-cli
  sentry-cli --version
  echo "sentry-cli is already installed. Skipping"
fi
```

I commented out the `CODEPUSH` and `GOOGLE` lines since they weren't present in the .env file. Let me know if that works for you.

**Comment by alexreyes** [comment]
Thanks @loganbek, that worked! I also had to change line 86 on ``postinstall.sh`` to work with the M1 processor: ``arch -arm64 brew install getsentry/tools/sentry-cli``. 

The rest of the instructions in the README work, including ``yarn start``. However, now that I have it open in Xcode I run it and the build fails. There are... a lot of warnings and 2 errors. 

<img width="276" alt="Screen Shot 2021-05-09 at 9 09 11 PM" src="https://user-images.githubusercontent.com/7016669/117593848-ce11e280-b10a-11eb-87ec-8567ae2fb2eb.png">

<img width="273" alt="Screen Shot 2021-05-09 at 9 09 20 PM" src="https://user-images.githubusercontent.com/7016669/117593856-d407c380-b10a-11eb-9fb6-6d8a03ca59be.png">

Did you find these? How did you fix it?

**Comment by loganbek** [comment]
⚠️Yep warnings on warnings⚠️,

Oh nice, I'm jealous of your M1. I believe the changes to `ios/Podfile` in this pull request will take care of your first ❌: https://github.com/rainbow-me/rainbow/pull/2000/files.

I'm not entirely sure on the second ❌ as I don't think I've encountered it before. What version of Xcode + PanModal are you using?

**Comment by alexreyes** [comment]
Wooo, thanks @loganbek that works! I had to reinstall the repo a couple of times but that PR helped me get it working on Xcode 12.5. Thanks!
