### ISSUE TITLE
Add support for custom networks (RPCs)

### ISSUE THREAD

**Issue by jpangelle** [rainbow-me/rainbow#2022]
When changing networks, would love to see the ability to add a custom network.

**Comment by skylarbarrera** [comment]
Hey @jpangelle ,

Thanks for the request! We get this one a a lot and its definitely on our radar! We are currently focused on adding more catered support for layer 2's and select side chains. This should be ready **very** soon™️ and hopefully it'll satiate you for the time being 🙂 

🌈

**Comment by jpangelle** [comment]
Great! Thanks for the response 😄
