### ISSUE TITLE
RecyclerListView white screen

### ISSUE THREAD

**Issue by savaskalkan** [rainbow-me/rainbow#2039]
Hi guys, when you select vb wallet in rainbow you are gonna see very long list in home page. And when you go down you are gonna see white screen and when you go top and you are gonna see white screen as well.

Do you have any idea to fix this or being more performance solution

![image](https://user-images.githubusercontent.com/12950142/118961392-f3a1b600-b96c-11eb-8611-fdba2a42495f.png)

**Comment by skylarbarrera** [comment]
Hey @savaskalkan,

Looks like you're using Coinburp which is a fork of 🌈 . As we are not affiliated, we do not provide support for them!

We'd encourage you to check out the Rainbow Wallet app as an alternative, We think you'll like it 🙂

**Comment by savaskalkan** [comment]
Hi @skylarbarrera  thank you for your message. Ss from coinburp but actually I am talking about rainbow app. It is not working properly in rainbow.

**Comment by skylarbarrera** [comment]
@savaskalkan please send the address and a screenshot of the issue in rainbow either here or to hello@rainbow.me and we'll take a look

**Comment by savaskalkan** [comment]
Hi @skylarbarrera , thanks for your interest.
I added 2 photos and 1 video about bugs I faced when I used the rainbow app.
If you wanna reproduce them you can add Vitalic's wallet in the app.

0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B

Thank you!

![rainbow1](https://user-images.githubusercontent.com/12950142/119674416-de34fc00-be44-11eb-865f-8be74c6bcbc7.jpeg)
![rainbow2](https://user-images.githubusercontent.com/12950142/119674422-decd9280-be44-11eb-9f99-c13f88d791e8.jpeg)

https://user-images.githubusercontent.com/12950142/119674426-df662900-be44-11eb-972e-ad182ab1689e.mp4
