### ISSUE TITLE
Can’t reach support

### ISSUE THREAD

**Issue by darnfish** [rainbow-me/rainbow#2069]
Been trying for a month now :~( what am I supposed to do?

**Comment by skylarbarrera** [comment]
hey @darnfish,

Sorry for not getting back to you! We are a very small team but have recently hired some people to help with support, can you share your email so we can find the ticket and reach out?

**Comment by darnfish** [comment]
My email is w.gibbo3@icloud.com :~)

Let me know if you need me to resend

**Comment by skylarbarrera** [comment]
We've got it, reaching out right now!

Thanks for your patience! 

🌈
