### ISSUE TITLE
Inconsistent behavior with personal_sign and eth_sign

### ISSUE THREAD

**Issue by rahulravindran0108** [rainbow-me/rainbow#2099]
I've been using WalletConnectSwift https://github.com/WalletConnect/WalletConnectSwift to interface with Rainbow and metamask wallet. It provides some helper functions for `eth_sign` and `personal_sign`. One thing I noticed is with `personal_sign`, rainbow wallet displays the hash of the message for confirmation while metamask shows up as human readable message. This behavior is replicated on `eth_sign` instead on Rainbow.

I feel `personal_sign` should include the human readable message as opposed to the hash right for confirmation on Rainbow ?

**Comment by brunobar79** [comment]
Can you include the payload of the request that you're sending?

Looks like the swift SDK is doing something different, since we DO show human readable messages for personal_sign requests.

You can try it at https://example.walletconnect.org which uses the JS sdk
