### ISSUE TITLE
Settings sheet collides with status bar on iPhone 12 mini

### ISSUE THREAD

**Issue by darnfish** [rainbow-me/rainbow#2110]
I'm seeing some white space that can be collapsed to fix this 😄

![image](https://user-images.githubusercontent.com/8293444/121681421-b5526f00-cab2-11eb-9646-5e5e2f3ece3d.png)

**Comment by skylarbarrera** [comment]
Hey @darnfish ,

Thanks so much for the report. Fixed here: https://github.com/rainbow-me/rainbow/pull/2111

Will be in our next release!
