### ISSUE TITLE
Rainbow.me search doesn't accept ENS name with suffixes other than .eth (bug report)

### ISSUE THREAD

**Issue by brantlymillegan** [rainbow-me/rainbow#2125]
On rainbow.me, when I enter a name like "brantly.eth" in the search bar, it works just fine. When I enter "brantly.xyz" or "brantly.art", the search fails even though those are ENS names set up exactly the same as brantly.eth. I assume this is because your system assumes all ENS names have the suffix .eth. In fact, your system should treat any dot-separated name as a potential ENS name and attempt a look-up on ENS. This will future proof it as the suffix namespace on ENS expands (it's already bigger than .eth, and it's about to get much bigger).

**Comment by skylarbarrera** [comment]
Hey @brantlymillegan ,

Thank for the ping, this was intentional for the MVP but is planned for our next big update to our web profiles along with some other ENS features we think you'll love.

🌈
