### ISSUE TITLE
Show image from an ENS name's avatar text record next to ENS name (feature request)

### ISSUE THREAD

**Issue by brantlymillegan** [rainbow-me/rainbow#2126]
An ENS name can have an image URL in its avatar text record. It would be great to display that image next to a name wherever it is displayed, whether it's as my Ethereum account profile image on the app homepage, on the rainbow.me NFT pages, or after I enter it a name in the recipient field when trying to send to it.

**Comment by skylarbarrera** [comment]
Hey @brantlymillegan ,

We've got some big plans regarding all of this with our upcoming native ENS integration, I'm sure we'll be in touch soon 🙂 

🌈

**Comment by shekhirin** [comment]
Hi @skylarbarrera, how's the things with ENS integration going?

Recently guys from ENS published an [avatar field format specification document](https://gist.github.com/Arachnid/9db60bd75277969ee1689c8742b75182) which might be useful for you. Uniswap [already implemented it](https://github.com/Uniswap/interface/pull/2321) with [Davatar React package](https://github.com/TBDAO/davatar-helpers/tree/master/packages/react).

Excited for Rainbow to support this! Let me know if I can help you.

**Comment by skylarbarrera** [comment]
hey @shekhirin!

this has been slightly on the back burner but we should be adding very soon. @brantlymillegan was actually in our office yesterday 🙂

keep your 👀  posted

🌈

**Comment by carlosdp** [comment]
Let us know if you want to use the upcoming @davatar/react-native library 😃

**Comment by albertaboy** [comment]
+1 would love to see this 🥺

**Comment by Soleone** [comment]
Any chance this could be re-opened? Seems worthwhile. There is some magic to the experience of connecting your address and it picking up all your ENS configuration.
