### ISSUE TITLE
Feature: add a way to generate the nth account of the mnemonic

### ISSUE THREAD

**Issue by hazae41** [rainbow-me/rainbow#2128]
+ In the accounts list, explicitly show the number next to the account address (if imported)
+ When generating an account, add an input for choosing the number

This would be a useful feature in itself and would be a great improvement for the Ethereum ecosystem, since users would be aware that accounts are deterministic

For example if I generate the 1234th account, I know that if I change my phone and generate the 1234th account, it will be the same

That's not currently the case, it feels like accounts are randomly generated

**Comment by FaysalM** [comment]
+1

**Comment by skylarbarrera** [comment]
Hey @hazae41 ,

Thanks for the request! We've got a full reorganization of how we display accounts coming soon that should be pretty close to what you're looking for! Stay Tuned!

🌈

**Comment by hazae41** [comment]
@skylarbarrera is this still in work?
