### ISSUE TITLE
[Question] How to add any ERC20 token?

### ISSUE THREAD

**Issue by jtrein** [rainbow-me/rainbow#2152]
I am attempting to add [`MUSE0`](https://etherscan.io/token/0xf75527cd04dda2816453552fec2fd43e4affac0c) to Rainbow iOS, but I do not see it in the list. Is there another way to add the token? I understand not all tokens have the same "level" of status 🤗, but it would be nice to have an alternative way to add ERC20 tokens which do not appear in the list. This would be similar to what [MetaMask allows](https://docs.metamask.io/guide/registering-your-token.html).

**Comment by skylarbarrera** [comment]
Hey @jtrein , 

We've actually working on this right now! Expect an update in the next couple weeks 😎 

🌈

**Comment by jtrein** [comment]
@skylarbarrera Hi there! Any update on the feature's implementation? Perhaps I missing something, but I still cannot add any ERC20 token.
