### ISSUE TITLE
App crash when clicking uniswap v3 in collection

### ISSUE THREAD

**Issue by tomsch** [rainbow-me/rainbow#2158]
When clicking uniswap v3 positions in collection the app is crashing. Can not open the App again, instant crash on startup. 

Only solution i found is to delete the app ans reinstall from app store.

**Comment by skylarbarrera** [comment]
Hey @tomsch,

Thanks so much for reporting!

We are aware and have fixed here: https://github.com/rainbow-me/rainbow/commit/f354d354f146dcaf246c2d614539738702ef37e0

Except an app update tomorrow with the fix 😊


🌈
