### ISSUE TITLE
[Question/Feature] Is there a way for another app to ask Rainbow for a signed message?

### ISSUE THREAD

**Issue by Clee681** [rainbow-me/rainbow#2198]
Native Web3 support for iOS and Android seems to be lacking. Is there a way (e.g. through deep linking) for another app to request a signed message from a Rainbow user? Ideally, after we link to Rainbow, the user could be redirected back to the initiating app.

Part of the motivation here is to avoid having to request the user's private key (i.e. seems appropriate that only a wallet should have that info).

**Comment by skylarbarrera** [comment]
Hey @Clee681 , 

We fully support WalletConnect and are implementing WalletConnect v2 for release soon.

Check out their docs, should have everything you need: https://docs.walletconnect.org/


🌈
