### ISSUE TITLE
Bug: Crash when no connectivity exists 

### ISSUE THREAD

**Issue by kdowlin** [rainbow-me/rainbow#2200]
If there is no connectivity on a device, the app will crash within about 10 seconds of open. 

https://user-images.githubusercontent.com/42585693/125960853-58a87c18-8ad1-4a3e-9524-ead5666a6c39.mov

**Comment by skylarbarrera** [comment]
Hey @kdowlin ,

Thanks for reporting! It looks like you are on an older version of the app, can you update and confirm it is still happening on the latest release?

Thanks 🌈

**Comment by kdowlin** [comment]
@skylarbarrera that is fixed. Do you know what PR fixed that? I'm working on a L2 wallet forked off rainbow and can't isolate that bug.

**Comment by skylarbarrera** [comment]
@kdowlin not entirely sure! Honestly don't think it was a conscious fix, we had a few regressions around the discover release.

Good luck with the L2 wallet!
