### ISSUE TITLE
Integration: Status Keycard

### ISSUE THREAD

**Issue by slavakurilyak** [rainbow-me/rainbow#2219]
I'm excited (and anxious) to see an integration with [Status Keycard](https://status.im/keycard/#:~:text=status%20is%20a%20private%20messenger%2C%20secure%20crypto%20wallet%2C%20and%20web3%20browser.%20keycard%20adds%20hardware%20security%20to%20the%20experience.).

> Status is a private messenger, secure crypto wallet, and Web3 browser. Keycard adds hardware security to the experience.

Inspiration: [The state of Ethereum wallets, with Rainbow's Mike Demarais](https://www.youtube.com/watch?v=HH7eQBTpvP8&t=1180s)

**Comment by tehacjusz19** [comment]
Hh

**Comment by tehacjusz19** [comment]
Hhh

**Comment by skylarbarrera** [comment]
hey @slavakurilyak ,

Thanks for the request, This is on our roadmap! We're still focusing on building out the core product but expect some updates regarding this in the coming months!

🌈
