### ISSUE TITLE
Having Issues Getting A Local Build On My Machine

### ISSUE THREAD

**Issue by benschac** [rainbow-me/rainbow#2231]
Hi 🌈,

I'm trying to get the project working locally, but I'm not having any luck. I ran through all of the steps. Setup the `google-settings.json`, created a `me.rainbow` project in the firebase console, the whole nine but I'm missing something.

This is my first bare react-native project so maybe I'm making some kind of n00b mistake.

#### Local setup
- Mac M1
- OSX: 11.4
- node: v14.17.3
- nvm: 0.35.2
- Xcode: Version 12.5.1 

`.env`
```
BRANCH_APP_DOMAIN=randomstring
BRANCH_KEY=randomstring
ETH_GAS_STATION_API_KEY=
ETHERSCAN_API_KEY=
INFURA_PROJECT_ID=
INFURA_PROJECT_ID_DEV=
IS_TESTING=true
ENABLE_DEV_MODE=1
DISABLE_REANIMATED=NO
IMGIX_DOMAIN=
IMGIX_TOKEN=
```

This is the error I'm getting:
```
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Analyzing workspace
note: Constructing build description
note: Build preparation complete
/Users/benjaminschachter/rainbow/ios/debug.xcconfig:1:1: error: unable to open file (in project "Rainbow")
/Users/benjaminschachter/rainbow/ios/debug.xcconfig:1:1: error: unable to open file (in project "Rainbow")
/Users/benjaminschachter/rainbow/ios/debug.xcconfig:1:1: error: unable to open file (in project "Rainbow")
/Users/benjaminschachter/rainbow/ios/debug.xcconfig:1:1: error: unable to open file (in project "Rainbow")
```

I took a couple of steps to try and fix the issue.
- https://stackoverflow.com/questions/55558984/xcode-pods-projectname-debug-xcconfig-unable-to-open-file-wrong-directory
But, that also didn't change anything.

Just curious if I'm missing something super small, or if anyone else on the team had a similar issue?

**Comment by ctjlewis** [comment]
@benschac, have you ran `yarn setup`?

**Comment by benschac** [comment]
Yep, I did everything sequentially in the docs.

I googled the error too w/o any luck. Is there anything specific/config to the build I might have borked?

**Comment by nicoglennon** [comment]
You can change the project's Debug configuration to "None" under the Info tab. If that still fails, change the Target's configuration to "None" in the same screen (the one that says `Pods-rainbow.debug` in the screenshot).

<img width="747" alt="Screen Shot 2021-07-27 at 5 32 15 PM" src="https://user-images.githubusercontent.com/16931094/127331791-85a4a211-dd44-4674-a82c-72fc6b3e5d8d.png">

**Comment by benschac** [comment]
wooooooooo yes. @nicoglennon ! 

<img src="https://user-images.githubusercontent.com/2502947/127413074-7c7e54c3-4ab6-412e-977c-17c7726a00ac.jpg" height="400" />


One other question. The app will open but I'm getting this error and then it'll close ASAP. Is there something else I need to do, or do I need to update my `.env` with all of the test keys? 

```
objc[87377]: Class CSAudioFileManager is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x143818288) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x1425faa08). One of the two will be used. Which one is undefined.
objc[87377]: Class CSNNVADEndpointAnalyzer is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/SpeakerRecognition.framework/SpeakerRecognition (0x143818cd8) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech (0x1425faf58). One of the two will be used. Which one is undefined.
```

**Comment by shawnmitchell** [comment]
> Hi 🌈,
> 
> I'm trying to get the project working locally, but I'm not having any luck. I ran through all of the steps. Setup the `google-settings.json`, created a `me.rainbow` project in the firebase console, the whole nine but I'm missing something.
> 

I'm also trying to get a fork of 🌈 up and running. Is there documentation anywhere about the Firebase project that needs to be created? I tried to make a firebase project called `me.rainbow` but that's not going super great either.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/3594613/155578652-1a6986db-9888-42a4-91a4-1ebe5a8ec438.png">
