### ISSUE TITLE
Add support for EIP-681

### ISSUE THREAD

**Issue by rahul-kothari** [rainbow-me/rainbow#2329]
This EIP suggests creating QR codes that represent a request to pay some amount of ETH/ERC20 on **ANY** evm like network - 
https://ethereum-magicians.org/t/erc-681-representing-various-transactions-as-urls/650

I am working for the EF Devcon team and this is one of the ways we want to facilitate selling our conference tickets.

I tried scanning a EIP 681 QR Code on rainbow's iOS app but it doesn't recognise the QR code for some reason

Would appreciate anyone looking into this!

**Comment by skylarbarrera** [comment]
Hey @rahul-kothari ,

Thanks for bringing this to our attention/ We added support for EIP-681 last week: https://github.com/rainbow-me/rainbow/pull/2343

Should work with the latest version in the app store!

🌈

**Comment by rahul-kothari** [comment]
Cool stuff!
