### ISSUE TITLE
No way to switch connected app's network to testnet

### ISSUE THREAD

**Issue by rudolfs** [rainbow-me/rainbow#2333]
Affected Rainbow App version: 1.5.19 (7).

In previous Rainbow versions it was possible to switch the test network globally via settings, now that value is ignored in the connected apps.

![IMG_9714](https://user-images.githubusercontent.com/158411/130051570-2242f758-5f5e-4cd2-9ab5-008b4f0a0514.PNG)

![IMG_9715](https://user-images.githubusercontent.com/158411/130051554-4a289051-dca8-46d1-bda1-ed9bc238cb1b.PNG)

**Comment by Artazor** [comment]
1.5.22 (iOS) The same problem

**Comment by Artazor** [comment]
Any idea of will it be fixed? (looks like a regression)

**Comment by beckywal** [comment]
> Any idea of will it be fixed? (looks like a regression)

I can walk you through the process on how how to get it fixed.

**Comment by skylarbarrera** [comment]
hey everybody,

thanks for reporting! I just put up a PR to fix: https://github.com/rainbow-me/rainbow/pull/2580

should be in the next app update,

🌈

**Comment by skylarbarrera** [comment]
hey everybody,

we just went live with WC testnet support in the latest update, you'll see a developer option in settings

🌈
