### ISSUE TITLE
`wallet_addEthereumChain` + WalletConnect not able to switch to Polygon

### ISSUE THREAD

**Issue by sbauch** [rainbow-me/rainbow#2356]
I use the `wallet_addEthereumChain` function to allow users to add and then switch to the Polygon network in my dapp.

I'm working on fixing up some Wallet Connect issues, and when I use Rainbow to connect to my dapp, my button that calls this function _does_ ask me to switch inside the app. But it seems like the switch isn't actually persisted.

Only if I go to my connected apps list and change the network there does the dapp recognize the wallet is on the correct network.

I recorded a video here with commentary to help explain -

https://user-images.githubusercontent.com/923033/131260452-a08c859d-2710-4e0b-8460-32f239f7e31e.mov

**Comment by skylarbarrera** [comment]
Hey @sbauch , 

Thanks for the report! We've added support here: https://github.com/rainbow-me/rainbow/pull/2361

Should be in the app store by the end of the week!

🌈
