### ISSUE TITLE
Is Rinkeby intentionally excluded from WalletConnect support?

### ISSUE THREAD

**Issue by akramhussein** [rainbow-me/rainbow#2386]
The following list excludes `Rinkeby` but I haven't been able to identify the reason. Is this intentional or can I create a PR to add it?

https://github.com/rainbow-me/rainbow/blob/18c56c1a21faa2bf30d206461cac63c5eb13b339/src/redux/walletconnect.js#L305

**Comment by beckywal** [comment]
> The following list excludes `Rinkeby` but I haven't been able to identify the reason. Is this intentional or can I create a PR to add it?
> 
> https://github.com/rainbow-me/rainbow/blob/18c56c1a21faa2bf30d206461cac63c5eb13b339/src/redux/walletconnect.js#L305

I can work you through on how to get this fixed
