### ISSUE TITLE
Old Uniswap transaction stuck in Pending state

### ISSUE THREAD

**Issue by unparalleled-js** [rainbow-me/rainbow#2396]
Type: Bug
OS: iOS 14.7.1

Hello! 

My wallet has a pending transaction since June that is not cancel-able, not able to be viewed on Etherscan, and cannot be sped up. It is listed in my transactions list but cannot go away. 

It is a Uniswap transaction.

The transaction has an identical one that did go through listed as well

I can share a screenshot if that is helpful

**Comment by estebanmino** [comment]
hi @unparalleled-js thanks for submitting this issue! I just pushed a PR fixing it.
