### ISSUE TITLE
walletconnect broke camera after notifications prompt

### ISSUE THREAD

**Issue by dereknelson** [rainbow-me/rainbow#2445]
hey team :)

i just tried to connect to my first app via scanning a walletconnect integration with dydx. because it was my first one, i was prompted me to enable notifications. after allowing, the camera element went completely black (still had the find code to scan) & it hung for a few minutes. 
  - navigating away didn't restore camera vision, only a full refresh did. 
  - i tried scanning again & was prompted by a different bottomsheet that loaded for a while only to tell me there may be a connection outage

lmk if i can add anything to this report!

**Comment by skylarbarrera** [comment]
hey @dereknelson, 

are you still experiencing this issue? If so can you send us a video and your phone model?

thanks!

**Comment by delsinpistonsxxx** [comment]
Yes I am 𝕯𝖊𝖑𝖘𝖎𝖓 𝕻𝖎𝖘𝖙𝖔𝖓𝖘Director of photography & Videography | CEO UnderDawg Media Group Ltd|GᗩY ᑭOᖇᑎ ᗰOᗪEᒪ |ᑭIᑎ-ᑌᑭ ᗰᗩᒪE | ᒪIᐯE ᑕᗩᗰ ᗰOᗪEᒪ|HOST OF SEX CAST 2 | INFLUENCER | @APAGunion MEMBER | SWISS NAVY BRAND AMBASSADOR| #DelsinPistons|  #CAM4Model  | #UnderDawgMediaLtd |#PayForYourPornCleveland, OHwww.delsinpistons.live| www.delsinpistons.cam | www.delsinpistonsxxx.com(SFW Social Media )Twitter |  Snapchat | Facebook  | Instagram*NSFW Social Media*My Stripchat | Chaturbate | Cam4 | Flirt4Free | Xtube | ModelHub | SexyJobs |My FancentroFor All my Sites vist thelink belowallmylinks.com/delsinpistonsIt is not our intention to send you email if you do not want it! If you have never visited our site, have not intentionally given us your email address, or believe you are getting our messages in error, please follow these steps to ensure removal from our database:  Sent from ProtonMail for iOS On Tue, Nov 23, 2021 at 9:02 PM, Skylar Barrera ***@***.***> wrote:  
hey @dereknelson,
are you still experiencing this issue? If so can you send us a video and your phone model?
thanks!
