### ISSUE TITLE
Not possible to select Goerli network on iPhone SE (2nd Gen)

### ISSUE THREAD

**Issue by mateuszsokola** [rainbow-me/rainbow#2512]
I was developing a WalletConnect integration for our app, and found out it isn't possible to change to `Goerli` network while using your mobile app.

```
Rainbow Version: 1.5.32 (3)
Hardware: iPhone SE (2nd Gen)
OS Version: 15.0.2 
```

Please check the video:
https://giphy.com/gifs/rUSE7eXSAmkvu2W4wO

**Comment by markusbug** [comment]
I got the same problem on my iPhone:

```
Rainbow Version: 1.5.33 (3)
Hardware: iPhone 11
iOS Version: 15.0.2
```

Is there any way I can debug this on my end? I would love to contribute

**Comment by outdoteth** [comment]
+1, really need this fixed.

```
Rainbow Version: 1.5.33 (3)
Hardware: iPhone 11 pro
iOS Version: 14.7.1
```

**Comment by skylarbarrera** [comment]
hey everybody,

thanks for reporting! I just put up a PR to fix: https://github.com/rainbow-me/rainbow/pull/2580

should be in the next app update,

🌈
