### ISSUE TITLE
Sending erc-20s from wallet are txn type 0 (non eip-1559)

### ISSUE THREAD

**Issue by clifton** [rainbow-me/rainbow#2521]
Thought #2436 would address this, but my last tx from my wallet was tx type 0 😢

**Comment by welps** [comment]
https://github.com/rainbow-me/rainbow/pull/2422 is actually the branch that will introduce EIP-1559 transactions and is currently awaiting review + QA

**Comment by clifton** [comment]
Thx much ❤️
