### ISSUE TITLE
SVG-based NFTs without a `viewBox` attribute don't fit within their bounding containers

### ISSUE THREAD

**Issue by jakeywan** [rainbow-me/rainbow#2530]
![IMG_7543](https://user-images.githubusercontent.com/1462496/140799283-5b55a8f6-bbc7-4ee9-b2df-8196c5dd8c3d.jpg)
![IMG_7544](https://user-images.githubusercontent.com/1462496/140799971-48d1714c-fe30-43d5-9b5d-0249e612bfa4.jpg)

I've confirmed this behavior with a few other folks as well, but it seems that a `viewBox` attribute is required to render SVGs properly, even though `viewBox` is not a required part of the SVG spec. I think it's safe to say that SVGs should always fit within their bounding container, not exclusively when a `viewBox` is present. 

SVG in question, as an example: https://storage.opensea.io/files/9b52c26860d69c51be439e72f4278f3b.svg

**Comment by skylarbarrera** [comment]
Hey @jakeywan,

We've got some svg improvements coming soon, but this one is tricky since the view box lets us know the assets dimensions, web has the same issue. 

We'll see if we can override and add support

🌈
