### ISSUE TITLE
[setup] yarn setup fails. possibly android related?

### ISSUE THREAD

**Issue by AndrewSB** [rainbow-me/rainbow#2538]
i just found out that rainbow is OSS! very cool 😄 thank you for putting this in the open 

i was trying to get a build going locally, but i keep getting failures from `yarn` on installing android packages, on the first try, it appears to fail to extract a file within `jsc-android`
```
[2/4] 🚚  Fetching packages...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/jsc-android/-/jsc-android-245459.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/Users/asb/Library/Caches/Yarn/v6/npm-jsc-android-245459.0.0-e584258dd0b04c9159a27fb104cd5d491fd202c9-integrity/node_modules/jsc-android/dist/include/JSVirtualMachine.h'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
error Command failed with exit code 1.
```

after a `yarn cache clean`, and re-`yarn setup`, a different file in `jsc-android` seems unhappy
```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/jsc-android/-/jsc-android-245459.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/Users/asb/Library/Caches/Yarn/v6/npm-jsc-android-245459.0.0-e584258dd0b04c9159a27fb104cd5d491fd202c9-integrity/node_modules/jsc-android/dist/org/webkit/android-jsc/r245459/android-jsc-r245459.aar'"
```

my env: 
macOS v12.0.1 on an apple silicon chip
node v17.0.1

my guess is that there may be an android setup step missing, as your team is working on adding android support, but im not sure. have any of you seen something like this? should i downgrade my `node` and report back?

**Comment by AndrewSB** [comment]
trying `brew install --cask adoptopenjdk/openjdk/adoptopenjdk8`, and downloading android studio to install an android SDK, as per https://reactnative.dev/docs/environment-setup

**Comment by welps** [comment]
Hi, I have not personally encountered this issue and can't reproduce, but someone who recently did has reported the following:

> If you get an error related to jsc-android, go to yarn.lock, CMD + F for jsc-android, and delete jsc-android from the 2 places it appears in yarn.lock

Can you try this and let me know if it worked for you?

**Comment by AndrewSB** [comment]
yup, that seems to have fixed. for posterity: 

error:
```bash
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/jsc-android/-/jsc-android-245459.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/Users/asb/Library/Caches/Yarn/v6/npm-jsc-android-245459.0.0-e584258dd0b04c9159a27fb104cd5d491fd202c9-integrity/node_modules/jsc-android/dist/org/webkit/android-jsc-intl/r245459/android-jsc-intl-r245459.aar'"
```

resolution:
```bash
rm '/Users/asb/Library/Caches/Yarn/v6/npm-jsc-android-245459.0.0-e584258dd0b04c9159a27fb104cd5d491fd202c9-integrity/node_modules/jsc-android/dist/org/webkit/android-jsc/r245459/android-jsc-r245459.aar'
```

and then re-running `npx yarn setup` works
