### ISSUE TITLE
Custom gas price for EIP 1559 transactions

### ISSUE THREAD

**Issue by zemse** [rainbow-me/rainbow#2539]
When entering a custom gas price, it creates a legacy transaction.

Currently, no option is visible to supply custom values for max base fee and priority fee. Maybe an "advanced" button be provided temporarily that displays a screen for entering custom gas values for the EIP1559 transactions until the UX is worked out.

**Comment by brunobar79** [comment]
Thanks for reporting. We're currently in the process of testing full EIP-1559 support, which hopefully will be released next week.
