### ISSUE TITLE
[BUG] - Wallet details are not being updated

### ISSUE THREAD

**Issue by pauloedurezende** [rainbow-me/rainbow#2543]
Hello guys! 👋🏻 

I recently performed an ETH transfer from Binance to my portfolio and noticed that there is a bug that affects the transaction history and the portfolio details regarding assets. Both items cited were not updating with the new correct information, only the wallet listings were updating the information of the total of ETH.

He could only update the information from the moment I go on camera to scan some QR code and go back to the wallet details, but the information vanishes if I refreshed this screen.

_P.S: For testing purposes, I created a new wallet where I transferred $0.01 cents to it, as in the video below, it doesn't show the transaction received let alone the portfolio details_

### Additional Information

Rainbow version: **1.5.33 (3)**
iOS version: **15.1**

### Video
https://user-images.githubusercontent.com/38743434/141213060-7241687b-99f1-4484-8571-143fde2e5e3d.mp4

**Comment by pauloedurezende** [comment]
Update: After a few hours (approximately 5-6 hours) on the same day, wallet updates started to arrive normally.

I will leave the issue open if anyone wants to investigate further into what the problem could be... 😄

**Comment by skylarbarrera** [comment]
Hey @pauloedurezende,

We're aware of this happening and have a bunch of people working on fixing 🙏 

thanks for the report!

🌈
