### ISSUE TITLE
ENS NFT not showing

### ISSUE THREAD

**Issue by samsisle** [rainbow-me/rainbow#2544]
My ENS name is not showing on https://rainbow.me/samsisle.eth.

Here is the ethscan → https://etherscan.io/token/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85?a=39210860448132921338695121807320419942374137856983462327137455187406685941173.

Any ideas what is going on here?

**Comment by welps** [comment]
We pull these from OpenSea (which you can see if you inspect the network requests on that page) and they're not showing anything for your address. Here's the request we make on rainbow-web for you: https://api.opensea.io/api/v1/assets?owner=0x0c141a42aae15cf0c5a4557b46561abf71205177&limit=50&offset=0&collection=ens

I think you may have to login there or something to trigger an index, but I'm not sure.
