### ISSUE TITLE
Transaction in polygon can't be confirmed

### ISSUE THREAD

**Issue by Sirdavos** [rainbow-me/rainbow#2587]
Deposit matic to in polygon network 
Connect quickswap via walletconnect
Try to make a swap 
Got notification in mobile app but can't confirm because of not enough eth

**Comment by ananth99** [comment]
Facing the same issue in iOS.

**Comment by welps** [comment]
Can you confirm the version being used in both cases here?

**Comment by Sirdavos** [comment]
I tested in IOS as well. Unfortunately I updated my IOS to 15 so app is updated as well and I can't give exact version I tested. I was using ISO 13 so it may be latest avaliable version for IOS 13

**Comment by welps** [comment]
OK, let us know if you experience the issue again since there were updates released, after your initial post, to address the behavior you described.
