### ISSUE TITLE
Launching iOS & Android from fork

### ISSUE THREAD

**Issue by matchback** [rainbow-me/rainbow#2609]
Hey guys,

Great Job on the wallet! 

I'm trying to get the iOS & Android versions of this app to run on simulators but i have not had much luck.

With Android i'm getting a compile error

**Android**

Script error: 

node_modules/lottie-react-native/src/android/gradle-maven-push.gradle': 46: unable to resolve class MavenDeployment 
   @ line 46, column 26.
             beforeDeployment { MavenDeployment deployment -> signing.signPom(deployment) }

**iOS**

Project Integrity issues (4 issues)
Target Integrity Issues (6 issues)

1. rainbow-develop/ios/debug.xcconfig:1:1: unable to open file (in project "Rainbow")
2. rainbow-develop/ios/Pods/Target Support Files/Pods-Rainbow/Pods-Rainbow.debug.xcconfig:1:1: unable to open file (in target "Rainbow" in project "Rainbow")

Please refer to my screenshot

Thank you for your assistance

**Comment by jasperwreed** [comment]
For ios It might be a good idea to remove cocoa pods and reinstall them.

```
pod deintegrate
pod install
```

I'm new to cocoa pods, but this was all I could find for similar error messages. Hope it helps :)

**Comment by nuoyz** [comment]
first add new file .env ;then yarn setup;

**Comment by shawnmitchell** [comment]
> first add new file .env ;then yarn setup;

any tips for setting up that `.env` file?

**Comment by matchback** [comment]
Have you guys ever got the Android version working yet?

**Comment by shawnmitchell** [comment]
I have not. I'm (sadly) stuck on getting my `.env` set up to the point that iOS version will launch in XCode

**Comment by nuoyz** [comment]
> > first add new file .env ;then yarn setup;
> 
> any tips for setting up that `.env` file?

follow Readme.md

**Comment by matchback** [comment]
Guys,

I’ve already launched the iOS version successfully. I need help with the
Android version
