### ISSUE TITLE
Test net Minting Error on Rinkeby

### ISSUE THREAD

**Issue by steverx** [rainbow-me/rainbow#2655]
failing to connect to the rinkeby network

---

accounts: ['0xa3d3b7f97aB0AcA3072A4161851Db89BcB292f7f']
bridge: "https://bridge.walletconnect.org/"
chainId: 1
connectCallbacks: []
connected: true
currentBlock: {number: Uint8Array(3), hash: Uint8Array(32), parentHash: Uint8Array(32), nonce: Uint8Array(8), mixHash: Uint8Array(32), …}
enable: ƒ ()
http: r {_events: o, _eventsCount: 2, url: 'https://mainnet.infura.io/v3/3c14df1609a041179c3f7004c74b446d%27%7D
infuraId: "3c14df1609a041179c3f7004c74b446d"
isConnecting: false
networkId: undefined
onConnect: ƒ (t)
qrcode: true
qrcodeModal: {open: ƒ, close: ƒ}
qrcodeModalOptions: undefined
request: ƒ (e)
rpc: null
rpcUrl: "https://mainnet.infura.io/v3/3c14df1609a041179c3f7004c74b446d"
send: ƒ (e,r)
triggerConnect: ƒ (t)
wc: r {protocol: 'wc', version: 1, _bridge: 'https://a.bridge.walletconnect.org/', _key: ArrayBuffer(32), _clientId: 'f396f323-63f6-4373-9e00-58a72bc61fff', …}
_blockTracker: r {_events: {…}, _eventsCount: 5, _maxListeners: undefined, _blockResetDuration: 8000, _currentBlock: '0xd228df', …}
_events: {block: Array(3), start: Array(3), stop: Array(3)}
_eventsCount: 3
_maxListeners: 30
_providers: (7) [o, r, r, r, u, d, {…}]
_ready: o {_events: {…}, _eventsCount: 0, _maxListeners: undefined, isLocked: false}
_running: true
connector: (...)
isWalletConnect: (...)
walletMeta: (...)
[[Prototype]]: f

**Comment by skylarbarrera** [comment]
hey @steverx , 

we currently don't support walletconnect with testnets, we have an open PR that adds support,: https://github.com/rainbow-me/rainbow/pull/2580 should be in the app in the next week or so.

Thanks for reporting,

🌈

**Comment by steverx** [comment]
well, that makes sense! lol. Should be no prob on main then?

**Comment by skylarbarrera** [comment]
yes mainnet & L2's should work as expected

**Comment by skylarbarrera** [comment]
hey @steverx ,

we went live with WC testate support in the latest update, you'll see a developer option in settings

🌈
