### ISSUE TITLE
`.env` setup tips and tricks

### ISSUE THREAD

**Issue by shawnmitchell** [rainbow-me/rainbow#2755]
This is a question, not a bug report. Really just want to see if we can get a little wiki for setting up the `.env` successfully on forks. A bit of color on what `BRANCH_APP_DOMAIN` and `BRANCH_KEY` are for, what kind of random string we want there, what `DATA_ENDPOINT` is and what to put there, is that like the Infura endpoint if we set up our project on Infura? 

Do we need `ETH_GAS_STATION` and `ETHERSCAN` and `INFURA` and `IMGIX` keys or is Infura alone sufficient?

**Comment by shawnmitchell** [comment]
would be really great to have a discord or a wiki here in github for people working on forks to share knowledge. I feel bad opening issues here that should really just be for reporting bugs in the main branch.

**Comment by kdowlin** [comment]
@shawnmitchell trying to do this from memory from our fork...

You can just leave randomstring for branch_app_domain & brand_key. 
BRANCH_APP_DOMAIN=randomstring 
BRANCH_KEY=randomstring 

DATA_ENDPOINT - I believe is the infura endpoint. 

You can get an eth_gas_station key for free: https://docs.ethgasstation.info/
Same with etherscan: https://info.etherscan.com/etherscan-developer-api-key/

I think you can get away with out an IMGIX api key, if I recall correctly.

**Comment by shawnmitchell** [comment]
@kdowlin Thanks! 

```
BRANCH_APP_DOMAIN=randomstring
BRANCH_KEY=randomstring
DATA_API_KEY=Demo.ukEVQp***********S873GMYHy
DATA_ENDPOINT=
ETH_GAS_STATION_API_KEY=a7948394e4302***********7042cf4610051a1982c4b
ETHERSCAN_API_KEY=WTZMQ12V**************WY7XZJ4XA
INFURA_PROJECT_ID=69c7a90c**********a8c4fbac
INFURA_PROJECT_ID_DEV=
IS_TESTING=true
ENABLE_DEV_MODE=1
DISABLE_REANIMATED=NO
IMGIX_DOMAIN=
IMGIX_TOKEN=
GOOGLE_SERVICE_API_KEY=AIzaSyBm8***********DrqfnkUBl08JQFbA
COVALENT_IOS_API_KEY=ckey_7c2**********8da2ed1
RAINBOW_TOKEN_LIST_URL=
```
This is where I'm at currently. I had the infura https endpoint there in `DATA_ENDPOINT` maybe the wss endpoint is better? Dunno if there are enough folks out there for a discord, but anyone who's successfully forked this awesome project, I'd love it if someone could reach out! Check my profile, twitter DMs are open.

**Comment by skylarbarrera** [comment]
DATA_ENDPOINT is for a WebSocket data endpoint 

mainnet rpc is ETHEREUM_MAINNET_RPC

will update .env.example soon
