### ISSUE TITLE
iOS app force quits after pressing "Add Funds" when weekly fund limit has been reached

### ISSUE THREAD

**Issue by internet-haruka** [rainbow-me/rainbow#2762]
I've exceeded my weekly limit for adding cash into Rainbow, and when I accidentally clicked it again, it force kicked me out of the app :( I tried this again just to make sure, and it happened again. I haven't exceeded my annual limit, so I'm not sure if it's an issue there as well.

iPhone 12 Pro / iOS 14.4.1

**Comment by welps** [comment]
While we are working on a fix for this, I've been told that uninstalling and reinstalling by our support team should fix this issue. Feel free to reopen and let us know if that doesn't work.
