### ISSUE TITLE
Argent wallet contracts support

### ISSUE THREAD

**Issue by shalzz** [rainbow-me/rainbow#2773]
Add an option to create an argent smart contract wallet on the on-boarding screen instead of creating an on-device private key and mnemonic backup flow.

This is now even more interesting considering the zksync support of the argent wallet contracts.

**Comment by skylarbarrera** [comment]
hey @shalzz 

we have no plans to add support for argent smart wallets. we are actively exploring smart contract wallets and multi-sig set ups but have yet to make any decisions

🌈
