### ISSUE TITLE
Update Project to Node v16

### ISSUE THREAD

**Issue by jasperwreed** [rainbow-me/rainbow#2785]
My main reason for this is that node v16 has prebuild binaries for Apple Silicon shipped with it. As time goes on and more developers are kinda forced to either get a silicon mac or move to windows / linux, updating the project now could allow for early testing / troubleshooting on these devices before more people pick them up.

**Comment by skylarbarrera** [comment]
hey @jasperwreed 

there are issues when using v16 for react native projects, we will keep an eye on it but don't plan on updating anytime soon
