### ISSUE TITLE
Can I fork Rainbow to create my own commercial wallet?.

### ISSUE THREAD

**Issue by ibrahimhasani** [rainbow-me/rainbow#2795]
Hi everyone, 
Trying to understand if a closed-source version that uses Rainbow wallet's codebase as its the starting point is completely fine? 
I went over the licensing document and this does seem to be the case.

Can anyone please comment?.

**Comment by welps** [comment]
Hi, none of us are lawyers and can give you these assurances. 

However GPLv3 is a very common license and there are resources from the primary source that you can reference in finding an answer:
- https://www.gnu.org/licenses/gpl-faq.en.html , more specifically https://www.gnu.org/licenses/gpl-faq.en.html#GPLCommercially
- https://www.gnu.org/licenses/quick-guide-gplv3.en.html

**Comment by jinchung** [comment]
> Hi everyone, Trying to understand if a closed-source version that uses Rainbow wallet's codebase as its the starting point is completely fine? I went over the licensing document and this does seem to be the case.
> 
> Can anyone please comment?.

As the documents @welps mentions: if you keep your project open sourced then yes; if close-sourcing it, then unfortunately no as per the license.
