### ISSUE TITLE
Swiping away transaction prompt

### ISSUE THREAD

**Issue by romangorelik** [rainbow-me/rainbow#2823]
So I am developing a dApp and using Wallet Connect to connect to Rainbow. Whenever I send a transaction using web3.js, a prompt comes up for the wallet user to sign. Click accept/decline will send a response back. However, you can also just swipe down the prompt, causing the transaction to hang since no response is coming back.

Can we disable this so that the user either has to accept or decline the transaction.

**Comment by shawnmitchell** [comment]
Or alternatively, perhaps swipe away == decline?

**Comment by skylarbarrera** [comment]
hey @romangorelik 

These requests are saved for the user on the top of their tx list( they do expire in 60 min), we find some users may want to perform other actions before signing or submitting a tx.
