### ISSUE TITLE
Incorrect fee and transaction cost displayed

### ISSUE THREAD

**Issue by cloudhead** [rainbow-me/rainbow#2926]
When using ETH as the base currency to denominate everything, the tx gas fees and costs are incorrect: they are dollar amounts that are shown as eth, eg. instead of $28 for a tx fee, it will show 28 ETH as the fee. And instead of $1000 as the amount being sent, it will show 1000 ETH.

**Comment by skylarbarrera** [comment]
@cloudhead should be fixed in the latest few updates!

Thanks for reporting,

🌈
