### ISSUE TITLE
Dan's Little Ideas for Rainbow

### ISSUE THREAD

**Issue by QuietImCoding** [rainbow-me/rainbow#2927]
## Just a list of some ideas I've had. Will probably keep updated to some degree but seems better to put them here than to keep tweeting @ you 

- [ ] NFT / Token Collections: For people that have large amounts of random tokens, this could help considerably reduce visual clutter and make finding things easier 
- [ ] Staked Asset Tracking: I'm actually not aware of any other applications that do this, but would be great if you could keep track of staked assets. You could probably do this by tracking certain kind of tx sent from a wallet and then showing them under a "staked" collection, maybe with an unstake button but at least with a link to the project
- [ ] Multi-send: Would be nice to be able to send tokens to multiple addresses at once, could maybe save on gas somewhat too. Similarly, selecting multiple NFTs to send to one address could be useful. 

Anyways I forgot the rest, but I'll just add them onto this thread when I remember. Hope you hare having a nice day, rainbow team!! <3

**Comment by skylarbarrera** [comment]
Hey @QuietImCoding,

Few of these are coming soon but will add the rest to our list! 

Thanks,

 🌈
