### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by malefic1950** [rainbow-me/rainbow#2966]
No matter what I do this pops up everytime. Please help me transfer my funds to other wallet
![17022645-6F85-4F76-84FA-DBB19464E182](https://user-images.githubusercontent.com/18112999/154840302-0107ff1e-25e6-4daa-854c-65889d0f529a.png)

**Comment by welps** [comment]
Hi @malefic1950 , since this is a customer related issue please reach out to support@rainbow.me
