### ISSUE TITLE
 magic-number corrections for fonts should use precision of 4

### ISSUE THREAD

**Issue by sambacha** [rainbow-me/rainbow#2986]
> ...applying some magic-number corrections for each font size — usually a decimal between 1 and -1. If you have any insight into why we need to do this, please let us know 🙏
> https://github.com/rainbow-me/rainbow/blob/aedc1160daade87140fba878122aa7a23ff67c72/src/design-system/typography/intro.docs.tsx#L36

 Rounding all values to a precision of `4` as evergreen browser implementations all utilize layout units that fall between 1/60th and 1/64th of a pixel.

[see https://trac.webkit.org/wiki/LayoutUnit](https://trac.webkit.org/wiki/LayoutUnit)
[additional ref, https://trac.webkit.org/wiki/LayoutUnit#Notes](https://trac.webkit.org/wiki/LayoutUnit#Notes)

[reference source, capsize.ts](https://github.com/seek-oss/vanilla-extract/blob/e69406ce0dbdc4616f4e4b8366f60b1277a7072f/site/src/capsize.ts)

**Comment by skylarbarrera** [comment]
I imagine there is reason for this cc @markdalgleish
