### ISSUE TITLE
German Localization

### ISSUE THREAD

**Issue by hEvaDer** [rainbow-me/rainbow#2999]
I could help you to translate the app into german! :)
I translated Bubki too, Mike knows me! :)
Cheers

**Comment by skylarbarrera** [comment]
hey @hEvaDer ,

Thanks for reaching out! We're working on setting up localization support and would love your help once we're ready!

Will reach out then,

Thanks! 🌈

**Comment by hEvaDer** [comment]
No problem, just let me know when it's time :)
