### ISSUE TITLE
Facing issue with iOS setup.

### ISSUE THREAD

**Issue by majorarif** [rainbow-me/rainbow#3131]
Hello dear,

I've cloned this application from develop branch. I've followed the instruction given in the readme file and tried to run the application.
With some difficulties I could successfully run the app in android emulator.

But I'm facing issues with iOS application while trying to run in simulator. It's not running but showing some error and failed.

It's showing 3 errors there 
1. In FBReactNativeSpec it shows,
Work/Xin: -c: line 0: unexpected EOF while looking for matching `''
Work/Xin: -c: line 1: syntax error: unexpected end of file
Command PhaseScriptExecution failed with a nonzero exit code

<img width="837" alt="Screenshot 2022-03-31 at 3 48 17 PM" src="https://user-images.githubusercontent.com/2860641/161027744-e0b374aa-d1f1-4ce6-afc0-2741d68b60ad.png">

2. In PriceWidgetExtension it shows,
Command CompileSwiftSources failed with a nonzero exit code

<img width="772" alt="Screenshot 2022-03-31 at 3 48 31 PM" src="https://user-images.githubusercontent.com/2860641/161027905-cb7d90df-c090-41e3-94f8-8576254eb707.png">

3. In SelectTokenIntent it shows,
Command CompileSwiftSources failed with a nonzero exit code

My environment is
Macbook pro M1 
OS version: 12.1
node version: v16.14.0
pod version: 1.11.2
xCode version: 13.2.1

Could any one give some idea what wrong I'm doing, or how can I successfully run the application in simulator?
If you need more information I'm ready to provide that.

Thanks in advance.

**Comment by bestvictorbusiness** [comment]
@majorarif I was also facing same issue ...
As far as I know, @benisgold might help us to resolve the above issues.

**Comment by lucas-grab** [comment]
Did you have any errors in setting up the project like in the readme? I fixed that by using `arch -x86_64 pod install` directly in the ios folder. The standard way of installing the pods with the install-pods yarn script didn't work on my M1 machine.

Now I have this error when running the 'Bundle React Native code and images' script. 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/11791883/165063322-2c44d901-463b-4bb7-b5e1-a9586bb9b778.png">


Would also really appreciate any pointers by the rainbow team!
Cheers
