### ISSUE TITLE
Bug on Android: Connection Expired after signing with WalletConnect

### ISSUE THREAD

**Issue by jamiely** [rainbow-me/rainbow#3145]
Device: Samsung Galaxy S10
Platform: Android 12
Rainbow: 1.0 (63)

## Error

**Connection Expired**
Please go back to the dapp and reconnect it to your wallet.

Sometimes I see an additional message:

WalletConnect session has expired while trying to send request status...

## Reproduction

I have a mobile app that requests a signature from Rainbow using WalletConnect. Every time I sign a message, it will show me the error above, and then either redirect me back to my app (or if it doesn't I return manually), then my app will register a successful signature. Since the signature is successful this is more of a UX issue.

## Screenshots

![image](https://user-images.githubusercontent.com/187039/161615567-1f0e7de6-08b3-4df0-aa79-29be0dbbb090.png)

Sometimes I see this message as well.
![image](https://user-images.githubusercontent.com/187039/161615630-bd609626-9683-4498-b62f-ab87a20dcf6a.png)

**Comment by Soleone** [comment]
I can replicate this on my end on an Android device. This seems like a regression because I haven't encountered this around a month ago.
