### ISSUE TITLE
Issue with large files

### ISSUE THREAD

**Issue by campionfellin** [rainbow-me/rainbow#3217]
Hello ranibow crew,

I would like to request a feature - please if I open an NFT to view, do not cache that it is "open", and by default whenever I close and re-open the app, make everything closed.

Issue - 

I own this NFT - https://opensea.io/assets/0xc4c377565a4b9eb6e657c2422bd33b6e4859b041/1

The image file is 65mb. I opened it once on my phone and it crashed the app. Now, whenever I open the app, it instantly crashes. Would be nice if we just forget this ever happened and please default to close them.

Additionally, I got an app update and it removed my wallet (which is fine, as I just use rainbow for read-only tracking my wallet). I re-added it and app crashed again. Can't remove or anything. Quite annoying. Anyway, fun bug!

Thank you :)

**Comment by welps** [comment]
@campionfellin It shouldn't be doing this anymore since https://github.com/rainbow-me/rainbow/releases/tag/v1.6.5 was released just to deal with this 65mb NFT, but I believe you may have to uninstall and reinstall the app (or clear out the app storage) for the fix to actually take.
