### ISSUE TITLE
Allow deletion of NFT collections

### ISSUE THREAD

**Issue by daweth** [rainbow-me/rainbow#3324]
A scam is occurring where a NFT is airdropped to a user. The user goes on the NFT website to check it out. It redirects back to rainbow for verification using Face ID, then all of a sudden you've just approved all of your USDC onto this website, which then proceeds to drain all of it from your wallet.

Yeah, this happened to me and I lost half of my savings.

I should be able to remove NFTs from view, or to separate a list of NFTs/Tokens called "airdrop". This way, users could be more dilligent and not make the same mistake I did.

**Comment by skylarbarrera** [comment]
hey @daweth,

we are currently implementing this feature, you can follow along here: https://github.com/rainbow-me/rainbow/pull/3659
