### ISSUE TITLE
Failing Segment API call breaks wallet connection (due to ad-blocking DNS)

### ISSUE THREAD

**Issue by pauldowman** [rainbow-me/rainbow#3342]
I use [NextDNS](https://nextdns.io/) and wallet connection with Rainbow doesn't work when it's enabled. (Rainbow opens but then does nothing. The "connect wallet" dialog doesn't pop up.)

Looking at the logs I can see that a call to api.segment.io is blocked. When I switch my DNS to 1.1.1.1 the problem goes away.

I assume this would also occur due to the Segment API call failing for any reason (e.g. their back-end being down).

This problem occurs on iOS. I don't have an Android phone handy right now but in the past this problem did not occur on Android.

**Comment by jkadamczyk** [comment]
Hey! From what I can see NextDNS has an easily accessible trial, could you please give me instructions on how to reproduce your issue?

Is it happening whenever you use Wallet Connect to connect to any dapp? The modal that allows you to connect is not appearing, but the app is launching normally right?

**Comment by pauldowman** [comment]
Yes the app launches normally, but the problem is that when using WalletConect the "connect wallet" dialog doesn't pop up. The app launches but then stays at the main screen.

So the steps to reproduce are:
1. Use NextDNS configured to block ads. 
2. Watch the logs in NextDNS
3. Use a dapp that supports WalletConnect
4. Connect wallet
5. See that Rainbow opens but doesn't give you the "connect wallet" dialog.

**Comment by jkadamczyk** [comment]
Thank you I'm going to import that into our internal system for verification soon. Thank you very much for the reproduction steps!
