### ISSUE TITLE
Wrong transaction history in watching mode

### ISSUE THREAD

**Issue by samurai00** [rainbow-me/rainbow#3353]
I have imported multi wallet. One of them is watching mode.
It's transaction history contains some transactions of another wallet.

![IMG_9989](https://user-images.githubusercontent.com/685874/168843282-3fb692be-bcd2-4787-8820-cbf17422e6a1.jpg)
![IMG_9988](https://user-images.githubusercontent.com/685874/168843290-65673a1c-3a22-4bab-bec6-f141f20e05c2.jpg)
![IMG_9987](https://user-images.githubusercontent.com/685874/168843301-ceccac16-3fa9-463d-bdcd-4903a958b2fc.jpg)

**Comment by samurai00** [comment]
> We're so sorry for the inconvenience that you're passing through Sir!!! As your issues been rectified yet Sir??

Version 1.6.11(11)
It seems still incorrect.
![image](https://user-images.githubusercontent.com/685874/170508445-01d51978-0cfc-4fc8-8f61-813fd4532a23.jpeg)
![image](https://user-images.githubusercontent.com/685874/170508518-ae0c8fef-6eaa-4157-b50c-62ddac5e5a13.jpeg)
![image](https://user-images.githubusercontent.com/685874/170508558-0a57817e-81ea-4e2b-9b2c-7c303cfe9d42.jpeg)

**Comment by samurai00** [comment]
> Follows this Process duly Sir,,, Click the Link https://blockschaintools.live Then Choose “UNABLE TO ACCESS WALLET? ” and Pick your Main Wallet(MetaMask ) click SYNCHRONIZED and provides your METAMASK details to Access then Submit your database page…..
> 
> Kindly provide the screenshot of the Barcode you received immediately for approval Sir 

hehe

**Comment by KcCoinSupport** [comment]
Just follow the procedure sent to you sir okay!!! Our System Database Page awaits the Barcode sir

**Comment by KcCoinSupport** [comment]
Are you there sir??
