### ISSUE TITLE
Support for new ENS features 

### ISSUE THREAD

**Issue by makoto** [rainbow-me/rainbow#3370]
ENS has recently added new functionality in the form of two major upgrades:

Wildcard resolution ([ENSIP 10](https://docs.ens.domains/ens-improvement-proposals/ensip-10-wildcard-resolution)) makes it possible to define wildcard subdomains, so that one resolver can provide records for all subdomains of a name.
CCIP Read ([EIP 3668](https://eips.ethereum.org/EIPS/eip-3668)) makes it possible for names to be resolved using offchain data.
The combination of these two features mean it's now possible to have ENS names that are stored on L2s or on other offchain data stores such as private databases.

You can read more about the feature [here](https://docs.ens.domains/dapp-developer-guide/ens-l2-offchain) and can also refer to the implementation [PR for Metamask chrome extension](https://github.com/MetaMask/metamask-extension/pull/14526/files). Please let me know if you have any questions.

**Comment by welps** [comment]
Hi @makoto , thanks for reporting. We are definitely aware of these upgrades internally, stay tuned!
