### ISSUE TITLE
Wallet transfer request showing MATIC instead of specific ERC-20 token

### ISSUE THREAD

**Issue by conradstephens** [rainbow-me/rainbow#3381]
I am using rainbow kit to trigger a token transfer of 0.05 USDC in my application on polygon. When the wallet pops open with the transfer details, it shows the amount being transferred in MATIC instead of USDC. However, when initiating the transfer, USDC is sent, so I know I am referencing the correct contract address of the token I want to send. When using metamask from rainbow kit, the correct token is shown so I am under the assumption it has something to do with the wallet of choice. I am using Rainbow wallet on Android (Samsung Galaxy S21 Ultra).

![Screenshot_20220523-085344_Rainbow](https://user-images.githubusercontent.com/20497723/169824607-f2de2cc4-dbfe-425a-a30e-377b910f4d30.jpeg)

**Comment by MarkOxpolygon** [comment]
I’ll have to refer you to the official support live chat,Kindly send a direct message to our live chat support forum on [Polygon Customer Support](https://forumpolygon.org/)  the best team will attend to you to ensure it is fixed as soon as possible. Thank you.

**Comment by KcCoinSupport** [comment]
We're so sorry for the inconvenience that you're passing through Sir!!!! As your issues been rectified yet Sir

**Comment by kevinji** [comment]
I ran into the same problem on ETH: the amount is correct but the units are wrong, so a 10 USDC transfer shows up as 10 ETH. The same transaction looks fine on MetaMask.

**Comment by skylarbarrera** [comment]
hey @conradstephens or @kevinji,

do either of you have an example dapp where you are seeing this issue? will take a look if there's a repro!

thanks!

**Comment by conradstephens** [comment]
My personal site that I am currently working on.

https://www.apollo5.dev/payment

Just click the submit button for the invoice number, then click on pay on polygon. After connecting your wallet, switch the network to polygon and make sure you have at least .05 USDC on polygon or it won't open prompt you to pay on the rainbow moblie app
