### ISSUE TITLE
‘Send’ Deep Link

### ISSUE THREAD

**Issue by davidmendoza-io** [rainbow-me/rainbow#3430]
Hello,

I am trying to create a deep link that initiates a SEND from the Rainbow Wallet. Ideally this deep link would have the token contract address, units being sent, and recipient address.

This is an example of a deep link from MetaMask, and hope to achieve the same with Rainbow Wallet:
http://metmask.app.link/send/${CONTRACT_ADDRESS}@137/transfer?address=${RECIPIENT_ADDRESS}&unit256={DECIMAL}e{PRECISION}

Any help would be greatly appreciated.

**Comment by skylarbarrera** [comment]
hey @davidmendoza-io,

we support the EIP-681 standard, you can play with creating those links here: https://brunobar79.github.io/eip681-link-generator/
