### ISSUE TITLE
Typo in "About Uniswap" section

### ISSUE THREAD

**Issue by Dmigit** [rainbow-me/rainbow#3452]
# Typo in Uniswap description🦄

## Issue

The description of Uniswap as an Automated Market *Market* should be corrected to Automated Market *Maker*. I know this seems like a small issue but it is in fact crucial to the app's reputation. I love the UI of the app and it's functionality but a typo can truly ruin everything, especially for a platform that contains sensitive information and is expected to be secure and especially for Uniswap, one of the most popular protocols in the Ethereum ecosystem.

## Screenshots
**In Rainbow:**

![IMG_8116](https://user-images.githubusercontent.com/86082012/171767124-f4ee38c0-54b6-4946-8bc1-7ee52d69aeb6.jpg)

**In official Uniswap website:**

<img width="706" alt="Screen Shot 2022-06-02 at 8 11 17 PM" src="https://user-images.githubusercontent.com/86082012/171767948-724a0f9d-35c4-4064-9a47-cd465e9942bd.png">

## Thank you

Thank you for taking the time to take my issue into account! This is the first issue I've made and I hope I can really contribute more to this platform and it's community.

**Comment by welps** [comment]
Hi, we've reported this typo to the data provider we use for token descriptions. Thanks.
