### ISSUE TITLE
node version: v14?

### ISSUE THREAD

**Issue by agnelnieves** [rainbow-me/rainbow#3548]
Idk if this was already documented somewhere, but is there a specific reason why the wallet is using node **v14.17.6**? 

**Considering v16.5.1** is LTS

**Comment by agnelnieves** [comment]
🤷🏻‍♂️

**Comment by pedrocruzio** [comment]
Hi, I'm also curious why this repo is using v14. Are there any specific libraries using node v14 instead of LTS?
