### ISSUE TITLE
Connection Failed on Rinkeby

### ISSUE THREAD

**Issue by slavakurilyak** [rainbow-me/rainbow#3639]
As a developer, I noticed that my Rainbow wallet was showing `Connection Failed` when I was testing my DApp using the Rinkeby network.

![](https://user-images.githubusercontent.com/6625584/176369238-b22b05d7-7b69-43c3-8592-97a948967f9b.JPG)

**Comment by skylarbarrera** [comment]
hey @slavakurilyak,

this is usually due to heavy walletconnect activity, everything should work fine if you try again.

closing this issue but feel free to respond with more info to repro on our end if thats the case!!

thanks,

🌈
