### ISSUE TITLE
Cannot run the app on iOS after cloning project

### ISSUE THREAD

**Issue by stefannovak** [rainbow-me/rainbow#3692]
After following the steps detailed to run this app on iOS, myself and a colleague, a senior iOS dev cannot get the app running. We have multiple issues.

First we have to turn off all debug configurations.
Issues with the Podfile. 

```
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In snapshot (Podfile.lock):
    SDWebImage (= 5.12.5, ~> 5, ~> 5.12.5)

  In Podfile:
    RNFastImage (from `../node_modules/react-native-fast-image`) was resolved to 8.5.11, which depends on
      SDWebImage (~> 5.11.1)

    react-native-palette-full (from `../node_modules/react-native-palette-full`) was resolved to 1.2.0, which depends on
      SDWebImage (~> 5)
```

Issues with 'duplicate symbols for architecture x86_64'.

Issues with a seemingly missing '#import <React/RCTEventDispatcher.h>' from a file, though we suspect this is because of underlying build issues.

We have tried to get this app running for over a day now. Could we please verify that the iOS build is okay? As at the moment, we cannot run the app following the README instructions.

Thanks.

**Comment by stefannovak** [comment]
Run 'yarn setup'. Lol.

**Comment by bczak** [comment]
this should be in README.md at least
