### ISSUE TITLE
Generated QR code isn't recognizable as a QR code. 

### ISSUE THREAD

**Issue by halversonmd** [rainbow-me/rainbow#3695]
I tried scanning the Rainbow QR code on iOS camera, the Rainbow iOS app, Metamask scanner, and Coinbase wallet app scanner.  None of these options recognize the QR code as a legitimate QR code. 

Here's a screenshot of my iPhone camera detecting a Metamask QR code and another of it unable to detect Rainbow's QR code. 

![IMG_7013s](https://user-images.githubusercontent.com/33351140/178552314-9b7e57d9-7b91-48c4-b24c-10a30ceed101.png)

![IMG_15D42E7E3303-1s](https://user-images.githubusercontent.com/33351140/178552773-accfa995-5cbd-455c-a6a3-41e56e31f5bb.png)

**Comment by DanielSinclair** [comment]
Looking into this @halversonmd! Could you send me the full 0x84 address? Checking if there are edge cases with a subset of addresses

**Comment by halversonmd** [comment]
@DanielSinclair of course: `0x84B04b5435C5cea62a534843f1C71Ed945b091eC`

**Comment by DanielSinclair** [comment]
@halversonmd Thanks for that. Yes, there is indeed an issue for certain addresses. The team will work on getting a fix out the door. In the meantime, you can share the QR Code available at the [Rainbow.me](https://rainbow.me/0x84B04b5435C5cea62a534843f1C71Ed945b091eC?qr=true) profile for this address

**Comment by halversonmd** [comment]
![0654CAB7-5708-4C1E-9636-505DAB282B4D](https://user-images.githubusercontent.com/33351140/179428868-8dd9dd98-05f2-46dd-8848-932ba1caa599.png)

@DanielSinclair here ya go.
