### ISSUE TITLE
Non-JSON EIP 712 Support

### ISSUE THREAD

**Issue by 0xcadams** [rainbow-me/rainbow#3714]
EIP-712 is becoming more common alongside SIWE, with applications using SIWE due to the user-friendly presentation in wallets. From SIWE, the only reason they chose to use EIP-191 was [due to lack of non-JSON support in wallets](https://blog.spruceid.com/sign-in-with-ethereum-wallet-support-eip-191-vs-eip-712/).

It would be great for Rainbow to implement a user-friendly display of EIP-712 data, so users are more aware of what they are signing and EIP-712 can mature to become a standard for login (while also retaining smart contract compatibility).

Didn't see any issues in the repo for this, so wanted to file one. Would love to help on getting a PR going, I'd imagine there's some complexity with implementing this.

**Comment by devli13** [comment]
Would love to see this added as well

**Comment by hbogit** [comment]
I feel the help. Honestly I have not figured it out yet.
