### ISSUE TITLE
Non-square profile picture is being stretched 

### ISSUE THREAD

**Issue by chrishobcroft** [rainbow-me/rainbow#4065]
When using a non-square (i.e. not 1x1 aspect ratio) image for the Avatar field in ENS, Rainbow stretches to fit into a 1x1, which looks "the opposite of beautiful"... you see:

![image](https://user-images.githubusercontent.com/2212651/186240666-72bbff3b-3fa7-418d-a510-5e6a58c41792.png)

The image looks like this:

![image](https://user-images.githubusercontent.com/2212651/186241620-6533f966-ac26-46d9-8c34-fd369b16b031.png)

Propose instead to crop to 1x1 around the centre, instead of stretching the canvas, like so:

![image](https://user-images.githubusercontent.com/2212651/186241468-153d0a75-d5fd-423d-b7b1-a643d0bcc010.png)

References:

https://rainbow.me/keimeyer.eth
https://images.squarespace-cdn.com/content/5aff363fc258b4f7879c0bf6/1561023794100-L0CRNHZSF21HFRAXOW2A/06_Keimeyer_1%C2%A9Raphael_Maxim_Guillou_dreh_cut_web.jpg
https://www.keimeyer.com/

**Comment by DanielSinclair** [comment]
@chrishobcroft Great catch! We'll fix this 👍

**Comment by TiegoEyes** [comment]
helpful

**Comment by DanielSinclair** [comment]
Looks like this became stale and was auto-closed @chrishobcroft. Implemented the fix; you'll see the change appear later tonight. Thanks for spotting 🫶
