### ISSUE TITLE
Unsupported Transaction Type `0x2`

### ISSUE THREAD

**Issue by sasicodes** [rainbow-me/rainbow#4081]
Context:

I tried to deposit some MATIC to Bundlr (https://bundlr.network) node (https://docs.bundlr.network/docs/client/js#fund-the-bundlr-node).

The transaction was initiated and after confirming it, it fails with an error,

```
code: -32000
message: "unsupported transaction type: 0x2 (operation=\"serializeTransaction\", transactionType=\"0x2\", code=UNSUPPORTED_OPERATION, version=transactions/5.6.2)"
```

I'm afraid it is wallet specific issue because the flow working in another wallet (MM)

Thanks

**Comment by TiegoEyes** [comment]
help

**Comment by sasicodes** [comment]
anyone?

**Comment by kasparkallas** [comment]
Running into exactly the same error message as well every single time and not able to figure out a fix.

What catches my attention is `version=transactions/5.6.2` but everywhere in my dApp anything ethers' related is 5.7.0+ (checked yarn.lock & node_modules thoroughly).

**Comment by kasparkallas** [comment]
I got it to reproduce deterministically.

This will always fail (using ethers v5 & TypeChain & wagmi & RainbowKit):
```ts
const contract = Contract__factory.connect(contractAddress, signer);
const firstPopulatedTx = await contract.populateTransaction.someFunction();
const secondPopulatedTx = await signer.populateTransaction(firstPopulatedTx);
await signer.sendTransaction(secondPopulatedTx); // This will fail when using Rainbow Wallet. Won't fail with most wallets though.
```

This won't fail:
```ts
const contract = Contract__factory.connect(contractAddress, signer);
const populatedTx = await contract.populateTransaction.someFunction();
const txResponse = await signer.sendTransaction(secondPopulatedTx); // Works!
```

I don't know the exact reason yet. The reason for double `populateTransaction` call is an intermediate SDK abstraction. As far as I know, this should be fine? This might be an ethers.js issue, not Rainbow Wallet's necessarily.
