### ISSUE TITLE
Wallet reset to old state, unable to retrieve mnemonic

### ISSUE THREAD

**Issue by rt2zz** [rainbow-me/rainbow#4101]
Steps taken:
- have a mnemonic (m1) set up and several wallets imported
- delete all wallets
- create a new mnemonic (m2) via the main welcome screen
- come back next day, see old m1 mnemonic and previously deleted addresses, but nothing for the m2 mnemonic.

How can I recover the m2 mnemonic? Is there a way to log all stored mnemonics?

**Comment by skylarbarrera** [comment]
hey @rt2zz,

thanks for reaching out, this should be doable! 

can you please reach out via email to support@rainbow.me for help with this?

thanks 🙏 


🌈
