### ISSUE TITLE
App icon not showing in modal

### ISSUE THREAD

**Issue by nabsta-eth** [rainbow-me/rainbow#4296]
![WC screenshot](https://user-images.githubusercontent.com/17034433/195719248-16ac1702-53b0-4f10-b51c-5f0bdfb1491a.png)
We use WalletConnect to facilitate connecting via wallets including Rainbow on mobile but the icon for our app isn't showing. I believe we have all metatags and manifest icons set so I'd like to know what is missing.

**Comment by DanielSinclair** [comment]
Hey @nabsta-eth! Send over some info about your dApp and we'll test it out and try to find a solution
