### ISSUE TITLE
WalletConnect + EIP-1559 - invalid object key: maxFeePerGas

### ISSUE THREAD

**Issue by tomholford** [rainbow-me/rainbow#4387]
Hello, I am one of the maintainers for a [PKI management dapp](https://github.com/urbit/bridge) which uses WalletConnect and EIP-1559.

When attempting to sign a transaction with a Rainbow wallet connected via WC, the following err is thrown:

```
invalid object key - maxFeePerGas (argument="transaction:maxFeePerGas",
```

See this comment for another example
https://github.com/urbit/bridge/issues/1070#issuecomment-1312632187

v1.7.9, iOS 16

**Comment by nickdaigler** [comment]
I'm also receiving this error fwiw.

**Comment by tomholford** [comment]
Bumping this issue - any updates on this?
