### ISSUE TITLE
Support in app browser

### ISSUE THREAD

**Issue by konojunya** [rainbow-me/rainbow#4408]
I suggest that an in-app browser, similar to Metamask, etc., would make it easier to use.

What would be nice to do for the in-app browser would be to generate a window.ethereum that would allow transaction authorization through a semi-modal or similar UI, rather than through wallet connect.

**Comment by DanielSinclair** [comment]
Thanks for the feedback Junya! This is something we've thought a lot about. Although the UX isn't where we'd like it to be just yet, we still have a lot of faith that dApp interactions in Safari/Chrome and native apps will be a better UX. Native apps like Farcaster have done some really cool things to make Sign-in with Ethereum with Rainbow and other wallets super smooth. We're also seeing success from newer wallets that built out Safari Extensions to make signing transactions in Safari just as easy as an Embedded Browser. But — interacting with contracts directly from a wallet is even better, and we'll be building more experiences like our support for ENS/Profiles and savings protocols like Compound.
