### ISSUE TITLE
Android: balance duplicated

### ISSUE THREAD

**Issue by skar395** [rainbow-me/rainbow#4446]
![Screenshot_20221205-075120.png](https://user-images.githubusercontent.com/50447537/205568007-1aa6474d-4d1f-4c06-80ab-cc9a243a70be.png)
In my wallet my balance is duplicated, the Ethereum network is shown twice

**Comment by DanielSinclair** [comment]
Thanks for the report @skar395. This has been resolved in an update that is shipping this week.

If you bump into this in the future, try a cache reset: https://learn.rainbow.me/missing-nfts#block-b6d222d807bf4b8da2ef7124c81f8e48
<img width="852" alt="Screenshot 2022-12-09 at 1 41 48 AM" src="https://user-images.githubusercontent.com/4412473/206641176-2767767a-17e7-4652-babf-80aa284114c7.png">
