### ISSUE TITLE
Rainbow setting wrong currency for payment link

### ISSUE THREAD

**Issue by RonanKMcGovern** [rainbow-me/rainbow#4475]
Rainbow is approving an ETH payment when it should be approving a 10 USDC payment. (This is not happening with any other wallet).

Payment link: https://www.trelis.com/payment/94987a45-589d-4e32-8ee2-e7fda94c4703

I'm showing screenshots of the approvals that Coinbase Wallet (10 USDC, correct) and Rainbow (10 ETH, completely incorrect) show for this same payment link.
![Uploading Coinbase.jpeg…]()

**Comment by RonanKMcGovern** [comment]
anyone else seeing an issue like this?

**Comment by juscamarena** [comment]
I see the same using wagmi setting at transfer event with an erc20 contract. Weird.

**Comment by juscamarena** [comment]
<img width="376" alt="Screenshot 2022-12-20 at 5 39 21 PM" src="https://user-images.githubusercontent.com/446261/208786970-77511edd-88ce-490f-8b5c-6fe4fe78a4fd.png">



<img width="380" alt="Screenshot 2022-12-20 at 5 39 32 PM" src="https://user-images.githubusercontent.com/446261/208786978-5190aa11-3eb2-4c40-9f32-4e86e2de24c2.png">
Sending a normal ETH transactions shows as an 'ETH request'

I sent a USDT transfer, which shows as a transfer, but as if it's sending ETH as well, oddly. @RonanKMcGovern

**Comment by RonanKMcGovern** [comment]
Yup, thanks @juscamarena . I think this is a pretty major bug. If you're trying to send 2 USDC and you accidentally send 2 ETH, that's a pretty big issue.

@DanielSinclair bringing this to your attention. Happening via wagmi, whether using walletconnect to connect Rainbow or using Rainbowkit to connect Rainbow wallet.

**Comment by DanielSinclair** [comment]
@RonanKMcGovern Thanks for bringing this to our attention. Was able to replicate the issue and it appears to solely be a display issue for Transfer requests. The underlying transaction values aren't impacted; here's a [test transaction](https://etherscan.io/tx/0xf6ed7f2063f058bf1ce87586f4d34bd11d6dc474849b348e0c91da82cc138363). Buy a coffee on us! Escalated to the team to rollout a bug fix.

**Comment by RonanKMcGovern** [comment]
Thanks! Appreciate it. I'll let you close this out once done. Thanks also @juscamarena for replicating

**Comment by buildtheui** [comment]
Hi there, I wanted to re-open this conversation, it's been three months since this bug was reported but I still see this problem, for both android and ios, thanks

**Comment by rgrchen** [comment]
+1. Would be amazing if this could be fixed soon. We have a use case where users can purchase products with Rainbow, but if a 10 USDC price displays as 10 ETH, then no one will complete the transaction. Many thanks.

**Comment by juscamarena** [comment]
I see the same with walletconnect on iOS when requesting a token payment.

**Comment by juscamarena** [comment]
The issue still shows with walletconnect 2 requesting an erc20 payment. The correct currency is not displayed say if requesting on the polygon network, requesting 20 USDC shows as 20 MATIC.

**Comment by skylarbarrera** [comment]
He!

this was fixed in the last release of the mobile app

sorry for the wait and thanks for everybody's patience 🙏 


🌈
