### ISSUE TITLE
Question: NFT Metadata caching policy

### ISSUE THREAD

**Issue by appleseed-iii** [rainbow-me/rainbow#4479]
As a developer if I update NFT Metadata under what conditions will Rainbow update the metadata cache? From what I can tell briefly looking through your repo you're pulling metadata ~~from OpenSea~~ directly from the contracts? https://github.com/rainbow-me/rainbow/blob/303ad32eaee1bd74d4f639e81ba0647a3c714124/src/ens-avatar/src/specs/erc721.ts#L26-L29 

Are there conditions I can trigger to force a metadata refresh?

**Comment by skylarbarrera** [comment]
hey @appleseed-iii ,

we fetch updated meta everytime u open the app or pull down to refresh

if your metadata is live and working on OS or other providers it should be live in rainbow as well

🌈
