### ISSUE TITLE
Support wallet specific deeplinks for payment URIs

### ISSUE THREAD

**Issue by juscamarena** [rainbow-me/rainbow#4488]
On iOS this works if rainbow is the only wallet or the default:

rainbow:ethereum:0x1658d51a0fDB0f6D8f1DD995821eD80B2A5e76F6@1?value=5.7e15&gasPrice=22&label=Bitrefill%20fe1b4055-b71e-4dbe-a2c6-10de2b24ff4d

If I set the app-specific deeplink rainbow doesn't parse the payment URI correctly. It'll open it up and do nothing.

rainbow:ethereum:0x1658d51a0fDB0f6D8f1DD995821eD80B2A5e76F6@1?value=5.7e15&gasPrice=22&label=Bitrefill%20fe1b4055-b71e-4dbe-a2c6-10de2b24ff4d

Metamask mobile has the same issue with:
metamask:ethereum:0x1658d51a0fDB0f6D8f1DD995821eD80B2A5e76F6@1?value=5.7e15&gasPrice=22&label=Bitrefill%20fe1b4055-b71e-4dbe-a2c6-10de2b24ff4d

But they have support for payment links through their universal links:

https://metamask.app.link/send/pay-0xdAC17F958D2ee523a2206206994597C13D831ec7@137/transfer?address=0x1658d51a0fDB0f6D8f1DD995821eD80B2A5e76F6&uint256=1e9

**Comment by DanielSinclair** [comment]
Hi @juscamarena! We do support this for the `ethereum://` deep links as you've discovered, but not for our `rainbow://` links. Could you walk us through your use case? We have concerns regarding the malicious abuse potential, so we've only added direct App Link support for read-only actions (like viewing an ENS profile). We may reconsider!

**Comment by juscamarena** [comment]
Hello,

I'm part of Bitrefill, we're one of the biggest crypto merchants in the space.

https://www.bitrefill.com/buy

We have web3 support and we are adding walletconnect for rainbow but ran into this issue for requesting tokens:

https://github.com/rainbow-me/rainbow/issues/4475

The reason I'd want this is that for iOS opening a payment URI set as ethereum: does not allow users to select the wallet to open. App specific deeplinks fix this. Not all users understand walletconnect and having a fallback to opening a payment URI directly to rainbow if a user selects the wallet in our wallet selector URI to have the best payment experience on iOS would help.

If a user with multiple wallets hits open wallet they'd expect rainbow to open, but it won't as iOS URI handling is the worst:

<img width="363" alt="Screenshot 2022-12-22 at 12 04 51 PM" src="https://user-images.githubusercontent.com/446261/209198014-e34d1d41-8909-442a-b48b-07bab720ca25.png">


I can understand the malicious abuse potential, but the same risk already applies with the normal ethereum: URI requesting payments with rainbow. If the user only has rainbow installed it'd be opened and a payment would be requested.

**Comment by RonanKMcGovern** [comment]
@juscamarena could you expand on what the specific malicious use potential is. Would be good for me to understand, thanks

**Comment by juscamarena** [comment]
> @juscamarena could you expand on what the specific malicious use potential is. Would be good for me to understand, thanks

It's the same as https://github.com/rainbow-me/rainbow/issues/4488#issuecomment-1362435501

Users can be tricked into sending funds. An example is those twitter bots saying to send 10 USD in ETH and get double back, and a payment request could be created that directly opens rainbow and requests the amount to an address. The same thing applies to regular URI payment requests without app-specific deeplinking.

This could also happen with walletconnect, but that one adds an extra step to confirm the wallet connection.
