### ISSUE TITLE
ETH balance showing twice

### ISSUE THREAD

**Issue by merc1er** [rainbow-me/rainbow#4494]
My ETH balance (on Ethereum - not side chain) is showing twice. My total balance sums up both ETH balances, making it incorrect.

![IMG_2052](https://user-images.githubusercontent.com/21960643/209082153-8a5927da-dd13-42a6-b233-59a32f7787b2.PNG)

Happening on latest iOS app.

**Comment by DanielSinclair** [comment]
Hey @merc1er! This looks to be a cache issue. A fix will be coming soon. In the meantime, clearing local storage with a Refresh (which doesn't affect your wallet keys) should resolve the issue: https://learn.rainbow.me/refresh-rainbow

**Comment by merc1er** [comment]
> Hey @merc1er! This looks to be a cache issue. A fix will be coming soon. In the meantime, clearing local storage with a Refresh (which doesn't affect your wallet keys) should resolve the issue: https://learn.rainbow.me/refresh-rainbow

Thanks! This worked (after clearing cache AND relaunching the app).
