### ISSUE TITLE
Deep links and web3 interactions not working

### ISSUE THREAD

**Issue by merc1er** [rainbow-me/rainbow#4512]
My Rainbow wallet (iOS - latest version) no longer shows modals when interacting with web3 apps/websites.

Here is an example with the OpenSea app:

https://user-images.githubusercontent.com/21960643/210493004-fc8cb7d3-22be-412d-afcb-57bf042d1395.mov

The same happens when scanning a QR code (via wallet connect or rainbow kit).

The app just opens and does not display any call to action. I tried deleting the cache and hard refreshing the app.

**Comment by DanielSinclair** [comment]
@merc1er Are you still experiencing this problem? What I think you're seeing here is WalletConnect request attempts failing. This can happen primarily because of Privacy VPNs or restrictive firewalls. We can investigate further if no VPNs are at play or other networks are working as expected.

**Comment by merc1er** [comment]
> @merc1er Are you still experiencing this problem? What I think you're seeing here is WalletConnect request attempts failing. This can happen primarily because of Privacy VPNs or restrictive firewalls. We can investigate further if no VPNs are at play or other networks are working as expected.

After inspecting my network, I see that when I try to connect to use Rainbow to connect to OpenSea, a query to branch.io is blocked (advertisers are blocked by my DNS provider).

That seems to be causing the issue. I wasn't sure at first as there is no error message in Rainbow, but I can now confirm it works when allowing all DNS queries 👍🏻

Also it seems only this connection uses branch.io as other wallets are able to connect fine to OpenSea (tested with Ledger Live and Enkrypt).
