### ISSUE TITLE
When is the web version coming? How can I contribute to it?

### ISSUE THREAD

**Issue by coding1101** [rainbow-me/rainbow#4533]

**Comment by DanielSinclair** [comment]
@coding1101 No Web Wallet on our roadmap right now, but we do allow you to see your NFTs at `rainbow.me/vitalik.eth` for any ENS or public address. We also have our Browser Extension just around the corner. Get notified when it lands with our waitlist: [https://rainbow.me/waitlist](https://rainbow.me/waitlist).

If you have any ideas of what you'd like to see with a Web Wallet, feel free to leave them here. We're certainly curious to explore that space!
