### ISSUE TITLE
ENV for testing/deploying locally

### ISSUE THREAD

**Issue by AndrewMohawk** [rainbow-me/rainbow#4565]
Hi,

I'm, interested in testing this release locally, but its difficult to figure out what are the requirements in terms of the ENV file. When building/running it seems some variables are missing, like `SECURE_WALLET_HASH_KEY` (?), but mostly it would be nice to know what should be used for each variable.

Is there a way we could get a descriptive for this file so we know what the minimum requirements would be to run this to say view a wallet and its assets?

Thank you!
-Andrew

**Comment by DanielSinclair** [comment]
@AndrewMohawk Unfortunately not something we'll have the bandwidth to support and document right now. An extensive list of API keys are needed to get the app running. Though many have succeeded! It's also designed to be built primarily in our CI environment.
