### ISSUE TITLE
iOS rainbow://wc regression

### ISSUE THREAD

**Issue by 10xSebastian** [rainbow-me/rainbow#4695]
It looks like the native deep-link `rainbow://` does not work for `/wc` (WalletConnect V1) anymore. 

https://user-images.githubusercontent.com/851393/222999352-51191c6e-7cb8-4f4f-8196-05c5afdcce9f.MP4

It would be great if native deep links remain usable.

Universal deep links are not sufficient and highly unreliable, see the following screenshots why:

<img width="744" alt="Screenshot 2023-03-05 at 18 10 02" src="https://user-images.githubusercontent.com/851393/222999392-be79918f-eef5-4a5f-8a2f-04949da70cd0.png">

On iOS universal deep links are optimistic, if internet connectivity is not sufficient or safari deems a universal link is not a direct trigger of a user click, it will send you either to the app store or will stay in safari without opening the native app at all. The "universal" in universal link, means that the content can be displayed in the browser, which is not true for a wallet connection and nobody should rely on universal links when connecting to mobile wallets on a mobile device.

**Comment by 10xSebastian** [comment]
This seems to be an iOS related issue, as connecting via native link `rainbow://wc` on android does still work.

**Comment by iketw** [comment]
It doesn't work for me on Android even. 

I think the issue may be related to how the URL is parsing the link here:
https://github.com/rainbow-me/rainbow/blob/fa964207751d8a4771d14210c7d58e70ed731eb3/src/handlers/deeplinks.ts#L81

For `https://` urls it works as expected but for `rainbow://` urls the host (and hence the action) is being set as empty.

**Comment by pharms-eth** [comment]
I am as well having issues with WalletConnect coming from a dAPP on iOS implemented in Swift.
I am getting this error even if I use the example WalletConnect provides in their Swift SDK
![image0](https://user-images.githubusercontent.com/100330083/228118124-7b45de21-34fe-43a3-b1e8-b76c0fe50deb.png)

**Comment by GloWE3** [comment]
As of 3/27 the rainbow app is no longer an option on some wallets and sites from what I noticed. Also, if rainbow is on a chain that the wallet that is being used as a home wallet there is a decline also which for a collector can be frustrating because all mints need to be done on a more older wallet I lost out on a few major items
