### ISSUE TITLE
Modal Screen overlapping notch in iPhone 14 Pro

### ISSUE THREAD

**Issue by sevenbytez** [rainbow-me/rainbow#4780]
Hey guys, firstly congrats by such a good product that Rainbow is, I've been using for quite a while and it's simply awesome.

As you guys can see in the image below, the majority of Modal screens are overlapping with the top notch in iPhone 14, and also makes difficult to tap the back button, as well reading the modal title.

![image](https://user-images.githubusercontent.com/30446226/230658952-f6e9dea5-5f9e-4c2a-b3ae-42734420a30b.png)

**Comment by sevenbytez** [comment]
I'm glad to take this issue myself, I just need help setting up the project locally.

**Comment by jkadamczyk** [comment]
Hey @sevenbytez thank you for the kind words and willingness to work on this. To my knowledge @benisgold fixed it a couple of days ago. I think it will be coming out with the next release. Byt no guarantees on that I am not 100% sure about it.
Once again thanks for your effort!
