### ISSUE TITLE
Podfile issues & MacOS builds

### ISSUE THREAD

**Issue by omertalib42** [rainbow-me/rainbow#4827]
Hi guys! I'm trying to build the project on my M1 air mac for a couple of hours, but I could not manage to do it. I'm having issues with podfile, and right now looking at the [commits](https://github.com/rainbow-me/rainbow/commit/8b5a4970b7cc285c5d324d3c3582fa95c0b2d67b) I see that you're also working on that. I tried many different approaches but none worked - it's either Podfile, or react that I failed.

Is there any way that I can run a version with my Xcode 14.3? If yes, is there any specific configuration that you use (that works)? I can also install an older Xcode version & older commit to my computer. So in short, I'm trying to build the app and have it running for a possible further development.

Thanks!

**Comment by omertalib42** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/56600661/235181273-fa1387d0-99d6-44a2-8d17-35d5dc68ec49.png">
Here's my podfile, if needed. I also tried setting debug to Pods-Rainbow as well, but it did not work.

**Comment by gessic-apps** [comment]
@otaliptus Did you ever figure this out?

**Comment by otaliptus** [comment]
@gessic-apps No, I eventually gave up trying.

**Comment by gessic-apps** [comment]
OK, @otaliptus , a year late, but I was having this problem now and figured it out. There's a lot of custom setup steps for this repo.

You have to run `yarn postinstall` , which creates the files you're missing. If you don't have a `.env` with the correct variables, it won't run.
