### ISSUE TITLE
WalletConnect v2 - fails to connect to optional chains

### ISSUE THREAD

**Issue by glitch-txs** [rainbow-me/rainbow#4872]
Rainbow mobile wallet does not connect to optional chains when using [WalletConnect's ethereum-provider package](https://github.com/WalletConnect/walletconnect-monorepo/blob/fcad757f8166efcae4ee43db08e3617e44f60582/providers/ethereum-provider/src/EthereumProvider.ts#L107)

The problem with this is that Wagmi uses [optional chains](https://github.com/wagmi-dev/references/blob/6aea7ee9c65cfac24f33173ab3c98176b8366f05/packages/connectors/src/walletConnect.ts#L295) for all the networks excepting the first one in config.

This prevents users from connecting to multiple chains at once when using wagmi's WalletConnect connector.

see [issue/discussion](https://github.com/orgs/WalletConnect/discussions/2480#discussioncomment-6029671)

Thanks

**Comment by glitch-txs** [comment]
there's a workound I think, which version are you using?

**Comment by nischitpra** [comment]
I'm using these packages with `WalletConnectLegacyConnector`
```
"wagmi": "^1.0.8",
"viem": "^0.3.37",
```

**Comment by glitch-txs** [comment]
Seems like it's related to Android only https://github.com/orgs/WalletConnect/discussions/2534?notification_referrer_id=NT_kwDOA_2SuLM2NjQ3MzA2NjIwOjY2OTQ5ODE2#discussioncomment-6100220

**Comment by nischitpra** [comment]
I'm using IOS 16.1.1 and I am facing the issue

**Comment by nischitpra** [comment]
Also the same thing works for walletct connects react app

**Comment by nischitpra** [comment]
Hey @glitch-txs any update on this?

**Comment by nischitpra** [comment]
I checked with the latest version of rainbow kit and not getting this issue. Seems to be resolved, thanks

**Comment by nischitpra** [comment]
@glitch-txs , So I tried with updated version, Its still not sending the optional chains. Previously I thought it was working but I was checking wallet connect v1 and not v2.

 
```
    "@rainbow-me/rainbowkit": "^1.0.2",
    "wagmi": "^1.2",
```

**Comment by Luzzotica** [comment]
Rainbow wallet seems to always respond to a connection request with the three chains it supports:
1. Eth
2. Polygon
3. Optimism

I assume it only supports these. I haven't been able to get it to connect to any others (Avalanche, fantom, etc.)

Which means no matter the optional namespaces, you get back those three.

I suppose that is a solution to the problem.

**Comment by skylarbarrera** [comment]
hey everybody, 

we added support for optional namespaces a few weeks ago so things should be working as expected now 

as for unsupported networks, all networks we support are listed here: https://github.com/rainbow-me/rainbow/tree/develop/src/networks

thanks for reporting 🙏 

🌈
