### ISSUE TITLE
WalletConnect V2 redirections issue

### ISSUE THREAD

**Issue by StevenBarnett1** [rainbow-me/rainbow#4884]
When using walletconnect v2 to initiate a connection / sign a transaction / do any sort of dapp - wallet interaction, rainbow does not redirect back to the dapp.

**Comment by StevenBarnett1** [comment]
Any update here?

**Comment by ignaciosantise** [comment]
@StevenBarnett1 Can you check if it's still happening in the latest Rainbow Wallet version?
