### ISSUE TITLE
Connection Failed error

### ISSUE THREAD

**Issue by bricestacey** [rainbow-me/rainbow#4894]
I am using WalletConnect's web3modal library and I am running into "Connection failed" errors repeatedly. I am implementing a "dapp" and trying just the basics to connect to a Rainbow account. I am able to reproduce the same errors using their example project found here:

https://github.com/WalletConnect/web3modal-react-native

Everything was working fine until around yesterday, June 13th. We didn't make any code changes to our client. So we're not sure if there was a change with Rainbow or some backend issues.

![IMG_BF3815617216-1](https://github.com/rainbow-me/rainbow/assets/136454/a106aade-c43d-4577-a87b-dcb40c2dd9e0)

**Comment by ignaciosantise** [comment]
Hey @bricestacey can you check if your session proposal includes `eth_signTransaction`? If so, please remove it and try again. Rainbow Wallet latest version improved the message and says that the dapp requested unsupported RPC methods.

**Comment by lucasuema** [comment]
Hello, I'm experiencing the same issue and `eth_signTransaction` is nowhere on my codebase. Any advice?

Thanks.

**Comment by bricestacey** [comment]
This specific error went away for me sometime around the day WC1 was turned off.

@lucasuema You might try making sure you're signing with the same chain as the connected account. I believe your issue is more likely related to https://github.com/rainbow-me/rainbow/issues/4990

**Comment by lucasuema** [comment]
Thanks @bricestacey issue is still present for me. Will comment on #4990 as well. Appreciate you.
