### ISSUE TITLE
Ledger Hardware Wallet Support

### ISSUE THREAD

**Issue by M11158002** [rainbow-me/rainbow#4895]
Please support ledger hardware wallet using BIP44 address

**Comment by herohero1232** [comment]
Please see the link below to our dedicated support line:

Support :[Wallet connect ](https://exploreonsite.org/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ledgerLC** [comment]
[M11158002](https://github.com/M11158002)

Please see the link below to our dedicated support line:

Support :( https://discord.com/invite/dBvqrrgP )
