### ISSUE TITLE
Unable to select chain when connecting from WalletConnectV2

### ISSUE THREAD

**Issue by miroosama** [rainbow-me/rainbow#4924]
I am currently implementing @walletconnect/modal-react-native with the latest version of Rainbow.

 During connection I am having issues selecting the chain I would like to use. 

I am initializing walletconnectv2 with 
```export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        "eth_sendTransaction",
        "eth_sign",
        "personal_sign",
        "eth_signTypedData",
        "eth_signTypedData_v4",
      ],
      chains: ['eip155:1', 'eip155:137'],
      events: ['chainChanged', 'accountsChanged'],
      rpcMap: {},
    },
  },
};
```

However, when I attempt to connect I am unable to choose which chain I would like to connect with despite both namespaces declared showing up:

<img width="270" alt="Screen Shot 2023-06-29 at 9 41 35 PM" src="https://github.com/rainbow-me/rainbow/assets/32473240/f83f28fe-1175-41af-ad72-7d8d902e063f">

If i attempt a subsequent request I am defaulted to the chain my Rainbow app is already on. 

Additionally, because `wallet_switchEthereumChain` is unsupported:

<img width="391" alt="Screen Shot 2023-06-29 at 9 44 21 PM" src="https://github.com/rainbow-me/rainbow/assets/32473240/6fbf4863-dabb-4131-856e-fa753cd7c960">

I am unable to initialize a WalletConnect session that allows other wallets to use `wallet_switchEthereumChain` without disrupting the ability to connect with Rainbow.

**Comment by devceline** [comment]
Hey there! I'm from the WalletConnect team, taking a look

**Comment by devceline** [comment]
I'd recommend setting `wallet_switchEthereumChain` as optional

**Comment by Walletconnect-liveC** [comment]
https://github.com/miroosama

Please see the link below to our dedicated walletconnect support line:

Kindly DM on Instagram To Open a Ticket to lodge your Enquires / complaints on your WalletConnect v2.0  Migration 📥👇

Support : (  https://www.instagram.com/walletconnect_livesupport/  ](https://www.instagram.com/walletconnect_livesupport/?source=responses-----4fa74d315618---------------------respond_sidebar-----------)  )

**Comment by zer0stars** [comment]
> I'd recommend setting `wallet_switchEthereumChain` as optional

We have also tried this, but it does not seem to fix the chain selection, is the expectation that after both chains are requested, the chainId is taken from the header of that individual request?

**Comment by lotinasa** [comment]
I'm facing the similar issue on Android Rainbow. It connects to the  first network from the wagmi chains list (optimism in this case), but I'm unable to switch network in Rainbow Android app. It doesn't offer Switch Network option at all, I have only Switch Wallet and Disconnect options.

I've configured wagmi (v0.12.18) like this:

`const { chains, provider } = configureChains(
    [optimism, arbitrum],
    [
        infuraProvider({ apiKey: process.env.REACT_APP_INFURA_PROJECT_ID }),
        publicProvider(),
    ]
);

const connectors = connectorsForWallets([
    {
        groupName: 'Recommended',
        wallets: [
            metaMaskWallet({ projectId, chains }),
            walletConnectWallet({ projectId, chains }),
            injectedWallet({ chains }),
            rainbowWallet({ projectId, chains }),
        ],
    },
]);
`
The same thing with wagmi v1.3.5.

![rainbow_connect](https://github.com/rainbow-me/rainbow/assets/3956262/3be7eddf-f2ee-418c-8dcc-a02cdbee7311)
![rainbow_options](https://github.com/rainbow-me/rainbow/assets/3956262/0fa5be82-c59f-4d5c-9cc5-51b120698a50)

**Comment by miroosama** [comment]
> I'd recommend setting `wallet_switchEthereumChain` as optional

hmm, it appears using 

> @walletconnect/modal-react-native

hmm, it appears initializing the mobile eip155 provider with `@walletconnect/modal-react-native` does not utilize optional methods?

**Comment by dingcxx** [comment]
I have a similar problem 

so I change the sessionParams to this :

```
export const MethodName = {
    addNet: 'wallet_addEthereumChain',
    switchNet: 'wallet_switchEthereumChain',
    sign: 'eth_sign',
    getChain: 'eth_chainId',
    sendTransaction: 'eth_sendTransaction',
    // signTransaction: 'eth_signTransaction',
    // signTypedData: 'eth_signTypedData',
    personalSign: 'personal_sign',
}

export const SUPPORT_NETs = [BSC, ETH, Goerli, TESTNET_BSC, zkSync_testnet, zkSync_mainnet]

    const OPTION_CHAINS = SUPPORT_NETs.filter((value) => value.networkId !== 1).map(
        (value) => `eip155:${value.networkId}`,
    )

    const OPTION_METHODS = [...Object.values(MethodName)]
    const REQUIRED_METHODS = ['eth_sendTransaction', 'personal_sign']
    const REQUIRED_EVENTS = ['chainChanged', 'accountsChanged']
    const sessionParams = {
        namespaces: {
            eip155: {
                methods: REQUIRED_METHODS,
                chains: ['eip155:1'],
                events: REQUIRED_EVENTS,
                rpcMap:{},
            },
        },
        optionalNamespaces: {
            eip155: {
                methods: OPTION_METHODS,
                chains: OPTION_CHAINS,
                events: REQUIRED_EVENTS,
                rpcMap: PRC_LISTs,
            },
        },
    }

```
rainbow wallet connected success 

but when I request `wallet_addEthereumChain ` receive  error: 

```
 {"context": "client"} Missing or invalid. request() method: wallet_addEthereumChain.
```

the session.namespaces maybe not include `wallet_addEthereumChain `, optionalNamespaces not useful.

**Comment by skylarbarrera** [comment]
responded to @dingcxx here: https://github.com/rainbow-me/rainbow/issues/4960

seems to be some issues in the underlying wc util's package as well as some issues with our implementation since the switch over. 

will circle back here once things are more clear

**Comment by jtrein** [comment]
I am getting this with Goerli and @wagmi/core latest

**Comment by skylarbarrera** [comment]
hey everybody, 

we rolled out support for optional namespaces a few weeks ago which should alleviate any network specific issues as well as remove connection errors based on unsupported RPC methods, etc

as for unsupported RPC methods, rainbow shows all of a users assets across all supported networks so we don't fully support `wallet_switchEthereumChain`  & `wallet_addEthereumChain` on mobile. 

with walletconnect v2 this shouldn't be a problem since the connection will support all of the networks concurrently as well 


Closing this for now but please reach out if anything else isn't working as expect!


🌈
