### ISSUE TITLE
Is it possible to set up wallet connect 2 on an older version of rainbow kit ^0.4.8

### ISSUE THREAD

**Issue by jtardioli** [rainbow-me/rainbow#4929]
I tried to migrate my app to the latest version for wallet connect 2 but its going to take me a long time to migrate as theres so many breaking changes in wagmi. Is there a way I can set up wallet connect v2 using this older version in the meantime?

I'm currently using

```
    "@rainbow-me/rainbowkit": "^0.4.8",
    "wagmi": "0.5.10"
```

**Comment by LendvaiPista** [comment]
4929
