### ISSUE TITLE
Unable to transact with dapp

### ISSUE THREAD

**Issue by dawar2151** [rainbow-me/rainbow#4953]
when i connect the app to dapps, it works well but when i send something to sign i receive the push notification but when i click on the notification it took me home page without pop up to sign.
Its something you're working on or an issue?

**Comment by skylarbarrera** [comment]
hey @dawar2151 

can you add some more info like the dapp you are using, iOS vs android. etc.

thanks

**Comment by dawar2151** [comment]
Hi @skylarbarrera ,

I'm using a reactJS Dapp, with an android but i tested also with IOS it doesn't work.

Thanks

**Comment by skylarbarrera** [comment]
can you please add the dapp url? we can't look into this without as likely this isn't a rainbow specific issue

**Comment by jinchung** [comment]
hi @dawar2151 following up on the dapp url that you were trying to use to connect - we have some improvements coming soon as well!
