### ISSUE TITLE
eth_signTypedData request

### ISSUE THREAD

**Issue by chendaxia65** [rainbow-me/rainbow#4956]
Hello, when I use WalletConnect V2 to sign the eth_signTypedData request, Rainbow did not give any response.

System: Android 10
WalletConnect V2 version: V1.13.0
Rainbow version: V1.8.24(178)

Request Data: (requestId=1689907270449432, sessionTopic=afde08bfe2983707ce0b396aec6fc1ae9f1bc00acf241b6fa6b10527a5c31420, method=eth_signTypedData, params=["0x5d827EEE04Ff97F4F8907D16cC8210d4ecbc7ed0",{"domain":{"chainId":1,"name":"Login","version":"1"},"message":{"contents":"www.openvoice.com wants you to sign in with your Ethereum account:\n0x5d827EEE04Ff97F4F8907D16cC8210d4ecbc7ed0\n\nSign in with Ethereum to the app.\n\nURI: https://www.openvoice.com\nVersion: 1\nChain ID: 1\nNonce: FEhfCpOGKmBrFJIl\nIssued At: 2023-07-21T02:41:10.406Z"},"primaryType":"Login","types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"}],"Login":[{"name":"contents","type":"string"}]}}], chainId=eip155:1)

**Comment by skylarbarrera** [comment]
if you have a test dapp I am more than happy to take a look, otherwise there is not much we can do to help
