### ISSUE TITLE
Exodus connect

### ISSUE THREAD

**Issue by Js8Uq0Iqu** [rainbow-me/rainbow#4977]
Hi. How to join desktop Exodus wallet v. 23.7.17 to https://rainbowbridge.app? I scan the code in my browser through the Exodus app and an error pops up 
"This QR code is for a different asset.  Please ensure you are using the correct wallet." 
I tried it on different networks. I need to transfer an Aurora token from the ETH network to the native network.

Browser Vivaldi
Desktop Manjaro 6.4.6-1

**Comment by jinchung** [comment]
Hi, I'll close this issue as you may need to reach out to the Exodus team for help - the bridge link you have is not associated with our app!
