### ISSUE TITLE
ERC20 transfer interpreted as ETH transfer (WalletConnect v2.0)

### ISSUE THREAD

**Issue by lassejaco** [rainbow-me/rainbow#4996]
Description:
Connecting to Rainbow Wallet (freshly downloaded) through WalletConnect v2.0 and initiating an ERC20 transfer is interpreted by Rainbow as an ETH transfer - e.g. (pic below) if I wanted to transfer 16,5 DAI, Rainbow will prompt the user a transaction transferring 16,5 ETH, which is a bit problematic to the say the least

<img width="338" alt="image" src="https://github.com/rainbow-me/rainbow/assets/75012246/3fa8a899-c365-483a-9567-a46b5300d8ea">

Happens for all networks.

Other wallets do not have the problem, so we suspect the issue is with Rainbow some way or another.

package versions:
```
"@wagmi/core": "^1.3.2",
"@web3modal/ethereum": "^2.6.1",
"@web3modal/html": "^2.6.1",
"viem": "^1.1.6",
```

Implementation
```
const { hash } = await writeContract({
  abi: erc20ABI,
  address: daiContractAddress,
  functionName: 'transfer',
  args: [0x..., amount]
})
``

**Comment by skylarbarrera** [comment]
Hey!

this was fixed in the last few app updates 

thanks for the report!


🌈
