### ISSUE TITLE
personal_sign requests seem to be failing silently in some cases 

### ISSUE THREAD

**Issue by L-Kov** [rainbow-me/rainbow#5036]
Working on adding rainbow wallet support for Polymarket but running into this issue: 

When connecting to rainbow via wallet connect v2 (via wagmi) and submitting `personal_sign` request with params: ["0x1c78982b939c88ca91014f810558a804f27f495a2a8c4198f494093c4af860d1", {address}] I get an app notification "Signature required - You have a message to sign" but when I visit the app see nothing to sign. Interestingly, this seems to be the case for any hex data that is not intended to be human readable. The hex string above is intended to be used to structure call data in for a meta transaction. When I try to call the `personal_sign` method for something more human readable ie "hi" or "0xhi" or "0x1c" I get no issues.

**Comment by nickbytes** [comment]
@L-Kov we're looking at this now. Is this in a new/unreleased Polymarket app? Our team was saying that it looked like signing worked in the Polymarket app, but curious if we're just not looking in the right place?

**Comment by L-Kov** [comment]
@nickbytes nope this is for the current version of the site (rainbow via magic). It only impacts specific flows where we use meta transactions that require the signing of hash data.

**Comment by L-Kov** [comment]
Hey @nickbytes just following up here, any progress on your end?

**Comment by jinchung** [comment]
@L-Kov Sorry for the delay - we've been wrapped up in some big feature work - we'll take a look at this next!

**Comment by jinchung** [comment]
@L-Kov the changes are under review and we expect to have them in an upcoming release shortly

**Comment by L-Kov** [comment]
thanks @jinchung @nickbytes this works perfectly. Rolling out some of our own fixes today and Polymarket should now work on Rainbow. Cheers!
