### ISSUE TITLE
Update @walletconnect/sign-client to 2.10.0

### ISSUE THREAD

**Issue by Sinu5oid** [rainbow-me/rainbow#5040]
### Motivation
As versions of @walletconnect/sign-client have simpler `sendResult` / `sendError` flow where the `relayer.publish` method is used without await, it's known to cause issues in handling responses on React Native wallets (the wallet responds to a session request, awaits for method to finish, and closes itself (navigates out of foreground state), which aborts pending network requests, and the DApp never receives a response)

### Please follow the issue discussion
* https://github.com/WalletConnect/walletconnect-monorepo/issues/3607#issuecomment-1711195868

**Comment by jinchung** [comment]
Thanks for sharing this! We've merged in the 2.10.x version update and it'll go in our next release!
