### ISSUE TITLE
Redirect back from Rainbow wallet to a DApp doesn't work on iOS 17 

### ISSUE THREAD

**Issue by maltsevoff** [rainbow-me/rainbow#5172]
The wallet doesn't redirect back to a DApp after successful approve of Connection or Sign request using WalletConnect. It doesn't work on iOS 17 but worked on iOS 16.

I'm using native iOS application which connect to the wallet. Also I provide redirect links in AppMetadata configuring WalletConnect sdk on the client. It could be parsed and used by the wallet to redirect back.

**Comment by walmat** [comment]
iOS 17 changed the way a few private APIs worked that we (and a lot of other apps) were utilizing for this. We're in the works of finding another solution to it.
