### ISSUE TITLE
ENS - DNS Domain Resolution

### ISSUE THREAD

**Issue by mozrt2** [rainbow-me/rainbow#5264]
Tested on: **Android App v1.9.11**

Issue: Rainbow doesn't resolve ENS in the `Send to` field when it is set up with a [DNS Domain](https://docs.ens.domains/dns-registrar-guide) such as `user.fkey.id` or `user.cb.id`. No suggestions appear and the rest of the screen stays blank. 

Reproduce: Open the Rainbow app -> Send -> Type in `moritz.fkey.id` or `moritztest.cb.id`

**Comment by mozrt2** [comment]
hi there, checking in here as this is still an issue

**Comment by walmat** [comment]
@mozrt2 This will require some internal changes from our ENS resolvers to support ccip reads which may or may not happen. Gonna close this for now, but will reopen if we it happens downstream from us.
