### ISSUE TITLE
wstETH on Base is not visible in the app

### ISSUE THREAD

**Issue by smol-ninja** [rainbow-me/rainbow#5286]
Context
--------

Rainbow seems to be supporting wstETH on Base network. During swap, you can select wstETH but after the purchase, it does not show up on the wallet page.

Issue
------
Since wstETH is supported in the swap functionality (inside the app) on Base network, it should be supported by the wallet page as well.

**Comment by skylarbarrera** [comment]
hey looks like its showing up now! please let us know if you're not seeing it 

🌈
