### ISSUE TITLE
Can't add more addresses from Trezor T

### ISSUE THREAD

**Issue by rafx85** [rainbow-me/rainbow#5290]
When I try to add addresses from Trezor T it sees only one. I use different path it finds it seems to be ok, but when I'm adding the second address it is not there and still only the first address is visible in the wallet. Same problem is with signing transaction, it fails despite I confirm on wallet.

**Comment by Vasually** [comment]
Hi @rafx85 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [defi protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)

**Comment by skylarbarrera** [comment]
hey are you using the https://github.com/rainbow-me/browser-extension ?

mobile app doesnt support Trezor atm!

**Comment by rafx85** [comment]
Yes ofc I'm using browser extension, I know mobile apps won't use trezor :D.
