### ISSUE TITLE
Avoid notification stacking in Android

### ISSUE THREAD

**Issue by drortirosh** [rainbow-me/rainbow#5301]
The purpose of notification is just too open the app. Once opened, the notifications should be removed
![Screenshot_20231221_155024_One UI Home](https://github.com/rainbow-me/rainbow/assets/40341007/43f927df-9753-46f1-b8f4-c037e9e18033)

**Comment by drortirosh** [comment]
I think this issue deserves some attention... it is annoying, yet probably easy to fix.

**Comment by skylarbarrera** [comment]
hey @drortirosh 

 we're taking a look, thanks for reporting!
