### ISSUE TITLE
eth-sig-util dependency need to be updated

### ISSUE THREAD

**Issue by vanya2h** [rainbow-me/rainbow#5320]
I see your wallet have strict version of `@metamask/eth-sig-util: "4.0.0"` in package.json. And this version must be updated since it does not support several typed data signature cases. I'm facing problem with this example of signature: https://gist.github.com/vanya2h/2d1ffbdd03f903156ea3f06be0fe87a7

Here's details https://github.com/MetaMask/eth-sig-util/releases/tag/v4.0.1

In general it's better to update to `v7.0.1` which have couple more fixes described here https://github.com/MetaMask/eth-sig-util/releases/tag/v7.0.1

**Comment by DanielSinclair** [comment]
@skylarbarrera For reference, we've adopted `7.0.1` on the browser extension already.

**Comment by skylarbarrera** [comment]
thanks for this! missed this over the holidays but will get it in : https://github.com/rainbow-me/rainbow/pull/5376
