### ISSUE TITLE
Connection to unknown network fails, but response seems successful

### ISSUE THREAD

**Issue by navFooh** [rainbow-me/rainbow#5403]
Using wagmi `2.6.x`

```typescript
import { getConnectorClient } from '@wagmi/core'

const { accounts } = await connect({ ... }, {
  chainId: 314159,
  connector: ...,
})
```

The network here is Filecoin Calibrationnet which is not present in the list of known networks for Rainbow Wallet. When connecting, the wallet shows an error:

<img width="151" alt="image" src="https://github.com/rainbow-me/rainbow/assets/394452/710a5cac-5e4b-4fe2-8f4c-28ae7b38bb25">

But also response with the list of `accounts` and does not throw an error in the code, making it look like the connection was successful.

**Comment by skylarbarrera** [comment]
hey @navFooh 
this looks to pertain to the rainbow browser extension: https://github.com/rainbow-me/browser-extension

this is the repo for the mobile wallet, please reach out there for help!

thanks!
