### ISSUE TITLE
theme generator

### ISSUE THREAD

**Issue by dalechyn** [rainbow-me/rainbow#5408]
RainbowKit offers a variety of css values to configure the theme, however it's not trivial to understand which color references which UI element.

It should be easy for user to set up a custom RainbowKit instance with as much of customization as user needs, without nearly touching the code unless neccessary.

One awesome dev (@zwergdev) has made the initial lift, yet a user should be able to see ALL the possible states where ALL the configurable properties come into play.
https://rainbowkit-theme.com/

Ideal UX is to just configure all the colors and properties within a UI and then copy the whole `theme` object with a single click.

It could be a separate UI, or as a hack, there could be a StoryBook which would allow to configure the values in it.

**Comment by skylarbarrera** [comment]
hey @dalechyn

**Comment by skylarbarrera** [comment]
hey @dalechyn,

This is really cool but pertains to https://github.com/rainbow-me/rainbowkit

please share there as this repo is only for the mobile wallet!


🌈

**Comment by dalechyn** [comment]
> hey @dalechyn,
> 
> 
> 
> This is really cool but pertains to https://github.com/rainbow-me/rainbowkit
> 
> 
> 
> please share there as this repo is only for the mobile wallet!
> 
> 
> 
> 
> 
> 🌈

Oh, I really have misclicked the tepo, sorry.
