### ISSUE TITLE
App navigation covered by Android navigation bar

### ISSUE THREAD

**Issue by bernaferrari** [rainbow-me/rainbow#5527]
Someone made the navigation bar hard-coded for Android phones that use the pill navigation, similar to iOS. If someone uses the standard navigation, it is incompatible:

![image](https://github.com/rainbow-me/rainbow/assets/351125/f71d8ac6-0723-4562-b98d-0294bf231e20)

**Comment by bernaferrari** [comment]
Sad no one wants to solve this

**Comment by bernaferrari** [comment]
What a shame no one cares about the most important aspect of an app

**Comment by walmat** [comment]
@bernaferrari ticketed this out and will tackle it this morning. What Android device are you using? Noticed this doesn't happen on my Nothing phone (2).

**Comment by bernaferrari** [comment]
S22, are you using the 3 button navigation?

**Comment by walmat** [comment]
> S22, are you using the 3 button navigation?

Yup. I've got a fix for it coming that I've verified works for 2 button and 3 button nav modes.

**Comment by bernaferrari** [comment]
Thanks!
