### ISSUE TITLE
WalletConnect

### ISSUE THREAD

**Issue by mnb21** [rainbow-me/rainbow#5548]
Why I cannot see Rainbow on the WalletConnect list wallets [here](https://stargate.finance)?

**Comment by ameerrah** [comment]
@mnb21 
 Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)

**Comment by leovido** [comment]
It seems to be showing now

<img src="https://github.com/rainbow-me/rainbow/assets/18484997/18232803-8502-4dac-9e3a-664d085da3bb" width="45%" />

**Comment by mnb21** [comment]
Yes, at the moment the wallet can be used there. Thanks.
