### ISSUE TITLE
Add ability to edit token approval amount

### ISSUE THREAD

**Issue by lofieth** [rainbow-me/rainbow#5550]
To ensure safety, it's best to set the token approval amount to match the transaction amount by default. 

Alternatively, we could incorporate a feature allowing users to adjust the token approval amount as needed. 

This would save many wallets from being drained.

See the example below:

![image](https://github.com/rainbow-me/rainbow/assets/134239349/cefc1386-a1d5-401b-b2f9-8ab5faecf82f)

**Comment by danielyoder77** [comment]
Yes, you make a very valid observation,  rainbow should consider this
