### ISSUE TITLE
Unable to send transaction on specific chain with wagmi

### ISSUE THREAD

**Issue by romanlv** [rainbow-me/rainbow#5564]
Our web3 supports multiple chains, and for browser extension wallets, correct chain can be switched to with `useSwitchNetwork` `wagmi` hook. 

With Rainbow mobile wallet (through WalletConnect), it fails to switch chain using wagmi hook (`'Missing or invalid. request() method: wallet_switchEthereumChain'`  https://github.com/rainbow-me/rainbow/issues/4924). As mentioned in related ticket 
>  ... rainbow shows all of a users assets across all supported networks so we don't fully support wallet_switchEthereumChain & wallet_addEthereumChain on mobile. 

If I skip network selection step, it attempts to send transaction to first network in the list (Arbitrum One instead of Base Sepolia in my case). I don't see a network selector anywhere in the mobile app. 

How to fix this problem? Is it even possible to send txn (mint) using Rainbow wallet?  

Note: i'm using `wagmi 1.x` (`usePrepareContractWrite/useContractWrite`) but tried with `wagmi 2.x`, and run into the same issue.

**Comment by Askedy** [comment]
Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL ](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)

**Comment by romanlv** [comment]
message above looks like a phishing

**Comment by romanlv** [comment]
seems to be a problem with testnets only

**Comment by romanlv** [comment]
confirmed: Rainbow mobile does not support any testnets, it's able to swtich to other mainnets
