### ISSUE TITLE
App fails to connect with Beefy Finance

### ISSUE THREAD

**Issue by JakeCooper** [rainbow-me/rainbow#5580]
Initial approval for Vaults seems to fail

After hitting confirm there's a lot pause (3-5s) followed by both a "Failed to send transaction" iOS modal, and an alert at the bottom with "Transaction canceled"

Verified functional on Ledger Live and Coinbase Dapps Browser

**Comment by Askedy** [comment]
Contact the Defi Protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL ](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)
