### ISSUE TITLE
ERC20 transfers show contract address instead of recipient as payment destination

### ISSUE THREAD

**Issue by vikanezrimaya** [rainbow-me/rainbow#5678]
In style of a greentext, because I'm feeling whimsical today:

> Be me
>
> Use Rainbow on Android via Play Store
>
> Update it to latest version to ensure this isn't fixed
>
> Have a wallet, from which I often transact in DAI
>
> Look into transaction history
>
> Wonder why am I not listed as recipient on an incoming payment in DAI
> 
> Look closer
>
> Observe that DAI transfers show DAI contract address as recipient

proofpic (if you look close enough, you will realize that my address should be listed instead of 0x6b17...1d0f): 
![image](https://github.com/rainbow-me/rainbow/assets/7953163/c9733603-8737-4fe2-8bb5-1dc58b4ac8a2)

**Comment by walmat** [comment]
Hey @vikanezrimaya I'll add this to my backlog. Sorry for the inactivity here! And thanks for letting us know.
