### ISSUE TITLE
Not able to connect with injected provider on dapp browser

### ISSUE THREAD

**Issue by gessic-apps** [rainbow-me/rainbow#5713]
I can't connect with rainbow on any of the dapps I try to open in the dapp browser, when I clone this repo and run it locally.

Steps to reproduce 

1 - Enable dapp browser in developer settings
2 - Navigate to any dapp (e.g. Pancakeswap
3 - clicking metamask tried to redirect to the meta mask app (WC give error to use metamask)

Expected Behavior:

1 - Ideally should show "injected" or "Browser" (e.g. on Pancakeswap)
2 - Choosing metamask or injected should show a popup in rainbow app asking to connect.

**Comment by bczak** [comment]
Hello, did you resolved your issue?
