### ISSUE TITLE
Welp's response to discussion of Rainbow's false advertising

### ISSUE THREAD

**Issue by DayOfShah** [rainbow-me/rainbow#5716]
I was notified by Welps that "People are deleting your posts because these are developer repos and not customer support forums." and that "Any support issues should be sent to [support@rainbow.me](mailto:support@rainbow.me) or https://support.rainbow.me/."

I wanted to thank Welps for this response. I also thought it was important to clarify that I did send communications to both of the aforementioned options, which still have yet to be acknowledged. It was only upon communicating via Github, did Rainbow provide a response.

Thus, I implore you to consider how attempting to communicate with Rainbow in private would result in any action. 

I understand that you likely have no ill-intent when closing these threads, and are likely doing so because you believe these communications are being posted in an incorrect setting. However, given the fraud that runs rampant in this industry, and the negative impact that such fraud has on the community at large, I kindly ask you to consider the importance of your employer being help accountable for engaging in the defrauding of its own community

However, out of respect for Welps, and others, a poll has been created and positioned in a manner, that hopefully does not interfere with the preferred structuring of Rainbow's Github. If you could all be so kind as to respond to this poll, it would be greatly appreciated. 

I hope you all have a great day. It shows great diligence for you all to be working on a Sunday. I wish prosperity and joy for you and your loved ones, even the ones actively defrauding the community.

**Comment by DayOfShah** [comment]
Thank you Welps!

**Comment by skylarbarrera** [comment]
hey @DayOfShah glad this got sorted!  Gonna close this, please reach out to the support email if anything else comes up 

sorry for the trouble,

🌈

**Comment by DayOfShah** [comment]
Please provide the transactions where Rainbow returned the funds

**Comment by mafiadavinci** [comment]
ohhhhhh. did u get the transactions?
