### ISSUE TITLE
Is Rainbow defrauding its community?

### ISSUE THREAD

**Issue by mafiadavinci** [rainbow-me/rainbow#5720]
Is it true Rainbow is falsely advertising "free mint" on its mobile app, but then charging individuals ETH, (distinct from, and in addition to, the transactional gas fee) without their knowledge or consent?

And then is it true Rainbow provides no means of communicating to resolve this matter except a singular support email which Rainbow ignores, when receiving communications regarding its false advertising?

Is it true Rainbow then gaslights its victims when they use Github to discuss their fraud, and misleadingly informs victims to communicate via the email address that Rainbow fails to adequately monitor?

Is it true that when Rainbow fails to resolve its fraud in a timely manner, and is provided an opportunity to resolve the matter amicably, Rainbow resorts to blocking its victims from Rainbow's Github (the only place where Rainbow responds to its victims)

Does Rainbow realize fraud is a crime in America?

Please ensure these questions are answered. Do not try to gaslight me.

**Comment by mafiadavinci** [comment]
I'm numbering the questions to make it easier for you to answer

1) Is it true Rainbow is falsely advertising "free mint" on its mobile app, but then charging individuals ETH, (distinct from, and in addition to, the transactional gas fee) without their knowledge or consent?

**Comment by mafiadavinci** [comment]
2) Is it true Rainbow provides no means of communicating to resolve cases involving Rainbow's defrauding its community members, except a singular support email which Rainbow ignores, when receiving communications regarding its false advertising?

**Comment by mafiadavinci** [comment]
3. Is it true Rainbow then gaslights its victims when they use Github to discuss their fraud, and misleadingly informs victims to communicate via the email address that Rainbow fails to adequately monitor?

**Comment by mafiadavinci** [comment]
4. Is it true that when Rainbow fails to resolve its fraud in a timely manner, and is provided an opportunity to resolve the matter amicably, Rainbow resorts to blocking its victims from Rainbow's Github (the only place where Rainbow responds to its victims)

**Comment by mafiadavinci** [comment]
5. Does Rainbow realize fraud is a crime in America?

**Comment by welps** [comment]
The user was refunded here: https://github.com/rainbow-me/fee-suggestions/pull/28#issuecomment-2108146076

A fix has been in progress here: https://github.com/rainbow-me/rainbow/pull/5700

I blocked you because you won't stop creating new issues and you are extremely rude. I will continue to block you for this reason. 

Our customer support is excellent. They check their email and we have the metrics to support this. We have no history of emails from you.
