### ISSUE TITLE
Connection failed on custom chain

### ISSUE THREAD

**Issue by matthew-t3** [rainbow-me/rainbow#5788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

1.3.6

### wagmi Version

1.4.13

### Current Behavior

We are using custom chain and authentication provider to allow users to login in our application, the rest of the wallet works fine except rainbowkit wallet (please see screenshot below). 

Redacted chain config:
```
const chain = {
  id: 99999,
  name: 'Custom network',
  network: 'custom',
  rpcUrls: {
      default: {
        http: [RPC_URL],
      },
      public: {
        http: [RPC_URL],
      },
    },
    blockExplorers: {
      default: {
        name: 'Custom Explorer',
        url: BLOCK_EXPLORER_URL,
      },
    },
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    }}
```

![438312469_1122479812314639_6982790215893505264_n](https://github.com/rainbow-me/rainbowkit/assets/157339328/27749e0e-97c9-4812-9d4a-50886f3dfa14)

### Expected Behavior

User should be able connect the rainbowkit wallet

**Comment by magiziz** [comment]
@matthew-t3 Rainbow wallet currently doesn't support custom chains. I'll close this issue for now, lmk if you have any questions 👍

**Comment by matthew-t3** [comment]
@magiziz Will it be supported in the future? Also, the custom chain is based on polygon CDK, is it still an issue?
