### ISSUE TITLE
First Time Send when it is not

### ISSUE THREAD

**Issue by EvilJordan** [rainbow-me/rainbow#5802]
![4vPbFYW0](https://github.com/rainbow-me/rainbow/assets/1364262/ea57510b-64b3-4e55-8f2c-4ca8e0238c47)

I've been sending to this address for over a year, using the Rainbow Wallet on iOS. It is not a "First time send" from this wallet.

**Comment by AdsRose** [comment]
Hello @EvilJordan 
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://supportethofficial.web.app/)

**Comment by grantatrainbowdotme** [comment]
Interesting, there are a few things that could cause that!

If you want to troubleshoot further, would you mind sharing the details (address sent from, tx hash, etc) on this issue with us in our support channel?

support@rainbow.me

**Comment by EvilJordan** [comment]
I'm shy and would definitely doxx myself with this particular address where things are happening... I guess I just need to be aware and if it happens from another wallet, I'll report :)
