### ISSUE TITLE
Unable to update ENS metadata through profile after updating Resolvers to ENS Recommended Public Resolvers

### ISSUE THREAD

**Issue by 0xsiddharthks** [rainbow-me/rainbow#5809]
Same as title.

- ENS: siddharthks.eth

- Updated Resolvers in the following tx: 
https://etherscan.io/tx/0x1982314f8bc206a70a67fcc6e8066568b04b2c399ff929a9e689e7a3528692e9
https://etherscan.io/tx/0xc12494b1d26bd7fff2bee2ce51b268d9bf74f822487f9361ea6468bcfc165ace

- Rainbow Tx to update Avatar: (This is still interacting with the default old resolver `0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41`)
https://etherscan.io/tx/0xc8f20698cd939d2d621154cbfb5be05b9da541557e2646e2eb344ca58ea5e303

- Custom Tx to change Avatar via ENS Official App: (This is interacting with the new resolver: `0x231b0Ee14048e9dCcD1d247744d114a4EB5E8E63`)
https://etherscan.io/tx/0x7f5bf40e4c5d7c4faebc34f8e239f3336345a7966e5c455715ef20cc9c1f4630

---------
App Details

OS: iOS
Version: v1.9.24 (Latest on the App store)

**Comment by grantatrainbowdotme** [comment]
Hi! 
For Rainbow profiles we are currently only using the old resolver: `0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41`

So the data written to that resolver should show up in Rainbow for the ENS profile.

We are looking to update this feature in the future to take advantage of all the new ENS features!
