### ISSUE TITLE
How can I generate an avatar by entering my wallet address and use it anywhere on the page?

### ISSUE THREAD

**Issue by yuanfa0620** [rainbow-me/rainbow#5935]
I need a function or method get a avatar

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @yuanfa0620
