### ISSUE TITLE
Wallet Connect deep links

### ISSUE THREAD

**Issue by SannikovMatt** [rainbow-me/rainbow#5937]
Hello,

I have an issue with a web browser's WalletConnect. It doesn't give me options to select Rainbow or BrowserWallet when I launch it locally. However, rainbow.me handles it fine.

Could someone please help me out with what I might be missing when I launch it locally?

I have WL_PROJECT_ID set.

According to the screenshot with code, we don't handle it through the URL in the WebView browser.

![Screenshot 2024-07-16 at 11 45 22](https://github.com/user-attachments/assets/5f3061b0-5c69-4327-bd61-81ef619cd270)
![Screenshot 2024-07-16 at 11 49 19](https://github.com/user-attachments/assets/44a52d53-c413-44bc-a077-5e38b5439cc3)

Any help would be appreciated. I have spent so much time trying to figure it out, and still nothing.

**Comment by bczak** [comment]
Have the same issue. Still trying to make it appear there with no luck

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Thank you for posting @SannikovMatt

**Comment by bczak** [comment]
> This issue has been preview on the Pull Requests. To resolve, Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/) Thank you for posting @SannikovMatt

Scam link, do not go there
