### ISSUE TITLE
[Maybe Bug] android rainbow wallet built-in browser failed to show wallet-connect url "https://wc:8b...@0.0.0.2/..."

### ISSUE THREAD

**Issue by diyism** [rainbow-me/rainbow#5946]
When I use the rainbow wallet built-in browser in android 10,
I open the "https://swap.defillama.com" and click "Connect Wallet" and choose "WalletConnect",
it redirects to a WalletConnect url: "https://wc:8b...@0.0.0.2/?relay-protocol=irn&symKey=dd4...",
but the raidbow built-in browser says: "Something went wrong",
if I open the WalletConnect url in system browser, it says "This site can't be reached",
how to resolve this problem?

**Comment by walmat** [comment]
Believe this was fixed with our recent work on Android Webview. Feel free to open again if you're still experiencing it.

**Comment by diyism** [comment]
@walmat Which version of android rainbow? I've tested the 1.9.36 on google play store right now, this problem is still there.

**Comment by diyism** [comment]
@walmat I've tested the latest 1.9.38, the problem is still there: when I click "connect wallet" and select "WalletConnect", the rainbow wallet built-in browser redirects to "https://wc:dfb38...@2?relay-protocol=irn&symKey=7fa4c..." and show "Something went wrong" on the page.
