### ISSUE TITLE
Hidden tokens are still counted in the total wallet balance

### ISSUE THREAD

**Issue by Gioxxy** [rainbow-me/rainbow#6079]
It would be helpful if hidden tokens did not affect the overall balance to better manage visibility and clarity for users.

### Expected behavior:
The total wallet balance should not include the value of any hidden tokens.

### Actual behavior:
Even though the token is hidden, its value is still being included in the total wallet balance. This gives an inaccurate representation of the wallet’s value when hidden tokens are meant to be excluded.

### Environment:
Version: 1.9.36 (16)
Platform: iOS 17.6.1

**Comment by QuimbyJr** [comment]
Hello @Gioxxy Send us a mail via generalresolution03@outlook.com for further review on this issue. 
note: kindly mark this issue as closed afterwards.
Regards

**Comment by walmat** [comment]
@Gioxxy can you check and see if this is still an issue on our latest release (1.9.41)? We've had a lot of user assets and balance stuff in the pipeline, so just want to verify this is still an issue for you before ticketing it out. Thanks!

**Comment by Gioxxy** [comment]
@walmat The issue still persists in the latest release (1.9.41).

**Comment by walmat** [comment]
> @walmat The issue still persists in the latest release (1.9.41).

Gotcha. We'll get it ticketed and in the pipeline. Appreciate your patience!

**Comment by walmat** [comment]
@Gioxxy this will mostly likely not go in this upcoming release, but next release.

**Comment by Gioxxy** [comment]
@walmat Hi, it seems that the problem has reappeared after the last update v1.9.72 (53).
