### ISSUE TITLE
[crash][bug] Tx signing issue with Rainbow Wallet Mobile - App crashes due to `gasLimit` Error

### ISSUE THREAD

**Issue by odcey** [rainbow-me/rainbow#6109]
# Description

We're experiencing a critical issue when attempting to sign transactions using Rainbow Wallet on mobile devices. While the transaction process works fine on desktop, the mobile app crashes immediately after the transaction goes through, due to a gasLimit-related error.

## Current Behavior
1. Transaction is initiated using Squid SDK (branch main-v2) with `Ethers.signer.sendTransaction(tx)`.
2. On mobile, the transaction appears to go through successfully.
3. Immediately after, the app crashes with the following error:

Error:
<img width="363" alt="image" src="https://github.com/user-attachments/assets/787ec097-a222-4628-ac6f-f8517082d657">

However our payload includes gasLimit 
`[...]  \"value\":\"100000000000000\",\"gasLimit\":\"621400\"}"`

4. The error is so severe that we cannot retrieve the transaction hash to show a loading state to the user.

## Expected Behavior
The transaction should complete successfully without crashing the app, allowing us to retrieve the transaction hash and update the UI accordingly.

## Additional Information
- The bug can be replicated doing a swap from Binance (and probably other chains) using squid app
- The `params` value in the error message is an actual, valid transaction hash (verified on the blockchain explorer).
- We believe this issue might be related to the fix in this commit: https://github.com/rainbow-me/rainbow/commit/56e95856d6a1a0cd9de34003550a306f0145eec6
  However, it seems this fix may not yet be deployed to production.

## Attempts to Debug
- Tried to debug the Android app locally, but encountered multiple errors:
  - Had to remove `customNetworkModule` import as it doesn't exist.
  - Encountered a GraphQL error when launching the app.

## Questions
1. Is the fix from the mentioned commit planned to be deployed soon?
2. Are there any known workarounds for this issue in the current production version?
3. Can you provide any guidance on successfully running the Android app locally for debugging purposes?

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@odcey

**Comment by odcey** [comment]
![Screen Shot 2024-09-18 at 10 25 03](https://github.com/user-attachments/assets/44e2ce2d-38ed-4d95-b186-4b171d84c559)

Ok scammers are everywhere apparently

**Comment by walmat** [comment]
@odcey I'm willing to take this on. Do you have a way I can reproduce this?

**Comment by odcey** [comment]
@walmat  Try to go on `app.squidrouter.com` within rainbow wallet on mobile, then try a transaction (like from Bsc BNB to Fantom FTM)

**Comment by odcey** [comment]
I've done another tx from BNB using the latest android version 1.9.41 and apparently this worked - you guys might have fixed it with that commit https://github.com/rainbow-me/rainbow/commit/56e95856d6a1a0cd9de34003550a306f0145eec6
Feel free to close
Thanks !

**Comment by walmat** [comment]
Awesome! Glad to hear it's fixed. Feel free to reopen in the future if it becomes an issue again. 🫡
