### ISSUE TITLE
QR Code don't take in consideration value

### ISSUE THREAD

**Issue by MajorTom327** [rainbow-me/rainbow#6260]
A QR Code with this value:

```
ethereum:0xE4a39B45f373FB8ae5D8932AC299Ab5206Cc718D?value=5000000000000000
```

This QR Code should set the params for a transaction as:
- Recipient `0xE4a39B45f373FB8ae5D8932AC299Ab5206Cc718D`
- Value: `0.005 ETH`

Currently the address is correctly set but the value is not populated.

Can provide a QR Code for tests if needed. Don't think it's a good idea to publish any qrcode here for security reason (Or being flagged as scam)

**Comment by Luizrebelatto** [comment]
can i take this problem to solve?
