### ISSUE TITLE
bug: deploying contracts breaks with rainbow wallet

### ISSUE THREAD

**Issue by siobh9** [rainbow-me/rainbow#6291]
In these 3 tickets we've consistently seen that rainbow wallet errors out when users try to deploy a contract with it - is deploying contracts a supported feature of rainbow wallet?

- https://github.com/jk-labs-inc/jokerace/issues/2735
- https://github.com/jk-labs-inc/jokerace/issues/2664
- https://github.com/jk-labs-inc/jokerace/issues/2853

**Comment by brunobar79** [comment]
Thanks for reporting. We'll take a look internally soon.  Closing this one since it's on the wrong repo but feel free to reopen on https://github.com/rainbow-me/browser-extension if you want to follow up
