### ISSUE TITLE
Isn't rn-nodeify supposed to be in devDependencies?

### ISSUE THREAD

**Issue by Kamalnrf** [rainbow-me/rainbow#939]
https://github.com/rainbow-me/rainbow/blob/047f2b8687e025161f6c4d8ec71d505bddebfd5d/package.json#L182

I just noticed this as a dependency which can be just a dev dependence, also something they mention in their README https://github.com/tradle/react-native-crypto#install

**Comment by brunobar79** [comment]
You're right! Thanks for catching that  🙌
